INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','A value for the {0} property was not provided.','Valoare pentru proprietatea {0} nu a fost furnizat.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','A value is required.','Valoare obligatorie.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Account Dashboard','tabloul contului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Account Informatio','Informatii contului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Actions','Действия');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add','Adaugă');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add Address','Adaugă аdresa');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add All Products','Adăugați toate produsele');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add another address','Adaugă altă adresă');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add another service to log in.','Adăugați un alt serviciu pentru a vă conecta.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add Attribute','Adăugați atribut');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add Comment','Adăugați un comentariu');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add Custom Link','Adăugați un link personalizat');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add Menu Items','Adăugați elemente de meniu');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add Optio','Adăugați o opțiune');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add products','Adăugați produse');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add Reply','Adaugă răspuns');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add Review','Adaugă o recenzie');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add to cart','Adaugă în coș');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add to Compare','Adăugați pentru comparație');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Add to Wishlist','Adaugă la lista de dorințe');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Added Attributes','Atribute adăugate');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Address','Adresă');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Address Book','Agenda de adrese');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Address Line 1','Adresa rândul 1');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Address Line 2','Adresa rândul 2');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Adjusted Quantity','Ajustarea cantității');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','All','Toate');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','All Categories','Toate categoriile');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Application Settings','Setări aplicație');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Apply','Aplică');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Approve','Aproba');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Approved','Aprobat');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Asociați-vă contul {0}.','Conectați-vă {0} contul.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Attribute Name','Numele atributului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Available Attributes','Atribute disponibile');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Available Options','Optiuni disponibile');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Back','Înapoi la');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Billing Address','Adresa de facturare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Body','Conţinut');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Brand','Marca');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Brands','Mărci');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Cancel','Anulare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Cancel Order','Anulează comanda');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Cart Price Rule','Regula prețului coșului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Cart Price Rule Usages','Reguli pentru aplicarea prețului în coș');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Cart Price Rules','Reguli Coș Preț');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Cart subtotal','Subtotal');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Catalog','Catalog');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Catalog.IsCommentsRequireApproval','Comentariile trebuiesc aprobate');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Catalog.IsProductPriceIncludeTax','Pretul include taxele');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Catalog.ProductPageSize','Numărul de produse de pe pagină');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Categories','Categorii');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Category','Categorie');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Category Mapping','Categorii');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Change','Editați');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Change password','Schimbați parola');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Change Password Form','Formular de schimbare a parolei');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Choose one','Alege una');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','City','Oraș');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Clone Product','Clonați produsul');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Code','Cod');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Comment','Cometariu');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Comments','Comentarii');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Configuratio','Configurare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Configure','Configurați');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Confirm new password','Confirmă noua parolă');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Confirm password','Confirmarea parolei');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Contact Area','Zona de contact');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Contact Areas','Zonele de contact');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Contact Name','Nume de contact');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Content','Conţinut');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Content Management','Management de conținut');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Continue shopping','Continuați cumpărăturile');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Count','Cantitate');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Countries','Țări');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Country','Țara');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','CountryId','Codul țării');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Coupon code','Codul cuponului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create','Creați');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create a new account.','Creați un cont nou.'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Address','Creați adresa'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Brand','Creați un brand'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Cart Price Rule','Creați o regulă coș preț'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Cart Pricing Rule','Crearea unei reguli de tarifare'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Category','Creați o categorie'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Contact Area','Creați o zonă de contact'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Country','Creați țară'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Customer Group','Creați un grup de clienți'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Menu','Creați un meniu'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Order','Creați o comandă'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Page','Crează o pagină'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Product','Creați un produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Product Attribute','Creați atributul produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Product Attribute Group','Creați un grup de atribute pentru produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Product Display Widget','Creați un widget de afișare a produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Product Optio','Creați o variantă de produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Product Template','Creați șablon de produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create State or Providence','Creați o zonă sau un district'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Tax Class','Creați un grup fiscal'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Tax Rate','Creați o rată de impozitare'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create User','Creați un utilizator'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Vendor','Creați furnizor'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Warehouse','Creați un depozit'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Create Widget','Creați un widget'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Created By','Creat'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Created','Data creării');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Cross-sell Products','Mărfuri încrucișate'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Current password','Parola actuală'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Current Price','Pretul curent'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Current Quantity','Suma curenta'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Current theme','Tema actuală');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Customer','Cumpărător'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Customer comments','Comentariile clienților'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Customer Groups','Grupuri de clienți'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Customer reviews','Recenzii ale clienților'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Customer Service','Serviciul clienți');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Dashboard','Panou de administrare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Date','Data'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Default shipping address','Adresa principală de expediere');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Delete','Șterge'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Delete Optio','Ștergeți varianta');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Descriptio','Descriere');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Discount','Reducere'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Discount Amount','Suma reducerii'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Display City','Afișați orașul'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Display District','Afișați zona'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Display Order','Afișează ordinea'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Display Postal Code','Afișați codul poștal');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','District','District');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Download','Descărcați');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit','Editați'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Address','Editați adresa'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Brand','Schimbați marca'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Cart Pricing Rule','Editați regula de stabilire a prețurilor'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Category','Editați categoria'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Menu','Editarea meniului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Page','Editați pagina'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Product','Editarea produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Product Attribute','Editați atributul produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Product Attribute Group','Editați grupul de atribute de produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Product Display Widget','Editați widgetul de afișare a produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Product Optio','Editarea variantelor de produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Product Template','Editarea șabloanelor de produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit User','Schimbați utilizatorul'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Vendor','Schimbați furnizorul'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Edit Warehouse','Editarea depozitului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Email','Posta electronică'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Enable Stock Tracking','Activați urmărirea inventarului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','End','Sfârșit'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Enjoy and see also','Bucurați-vă și vedeți și'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Enjoy and take also','Bucurați-vă și luați, de asemenea');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Enter your email.','Vă rugăm să introduceți adresa dvs. de email.'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Entity Name','Denumire');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Export','Export'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Export Orders','Comenzi de export'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Export Orders with Order Lines','Exportul comenzilor cu numerotare'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','External Logins','Conectări externe'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Filter by','Filtreaza dupa'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','find by commenter','găsiți după comentator'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Fixed amount discount for whole cart','Suma fixă ​​a reducerii pentru întregul coș');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Forgot your password?','Ați uitat parola?');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','From','De la'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Full name','Numele complet');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','FullName','Numele complet'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','General Informatio','Informații de baza'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Generate Combinations','Generați combinații');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Global.CurrencyCulture','Format monetar');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Global.CurrencyDecimalPlace','Numărul de zecimale');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Global.DefaultCultureUI','Localizare implicită'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Go to shopping','Continuați cumpărăturile'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Has Options','Optiuni disponibile');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Hello {0}!','Felicitări, {0}!');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Home','Acasă'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','hone Number','Număr de telefon');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Id','Id');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Images','Imagini');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Import','Import'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Include in menu','Includeți în meniu'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Incomplete orders','Comenzi nefinalizate');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Informatio','Informație'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Installed themes','Teme instalate');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Inventory','Inventariere'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Is Active','Activ'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Is Allowed To Order','Permis la comandă'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Is Billing Enabled','Facturarea este activată'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Is Called For Pricing','Contact pentru clarificare preț'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Is Featured','In curand'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Is Published','Publicat'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Is Shipping Enabled','Transport inclus'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Is Visible Individually','Vizibil în mod individual');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','IsEnabled','Pornit');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','IsSystem','Sistemic');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Items','Elemente'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Latest orders','Ultimele comenzi');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Link','Link');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Localization.LocalizedConentEnable','Localizarea conținutului inclusă'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Login ','Intrați'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Log off','Ieșiți');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage','Control'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage address','Gestionarea adreselor'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage Contact','Managementul contactelor'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage Contact Area','Managementul zonei de contact');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage Cross-sell Products','Managementul produselor cross-selling'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage News Categories','Managementul grupului de știri'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage News Items','Managementul știrilor'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage products in warehouse','Managementul depozitului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage Products Selection ','Gestionați produsele selectate'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage Related Products','Managementul produselor conexe'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage Translations','Setări de traducere'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manage warehouse products','Managementul depozitului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Management products for warehouse','Conectarea mărfurilor la depozite'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Manager of Vendor','Manager furnizor');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Managers','Managerii'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Max Discount Amount','Suma maximă a reducerii');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Maybe the page was moved or deleted, or perhaps you just mistyped the address.','Posibil pagina a fost mutată sau ștearsă sau poate că tocmai ați introdus adresa greșită.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Menus','Meniul'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Meta Description','Descriere'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Meta Keywords','Cuvinte cheie'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Meta Title','Titlu'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Most search keywords','Cuvinte frecvente de căutare'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Most searched keywords','Cele mai populare cuvinte cheie'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Most viewed products','Cele mai vizualizate produse '); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','My Settings','Setarile mele');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Name','Nume'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','New Old Price','Nou preț trecut'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','New password','Parolă nouă'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','New Price','Preț nou');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','News.PageSize','Dimensiunea paginii de știri');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','No','Nu'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Not Approved','Neaprobat'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Not available','Nu este disponibil'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Not Vendor','Nu este furnizor');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Note','Notă'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Note that the updated translations only be affected after the application is restarted','Vă rugăm să rețineți că traducerile actualizate vor fi aplicate numai după repornirea aplicației.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Null value is invalid.','Valoare nulă este nevalidă.'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Number of Products','Numărul de mărfuri'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Old Price','Prețul trecut'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Option Combinations','Opțiuni de combinație');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Order','Comandă'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Order By','Filtrează după'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Order Detail','Detaliile comenzii'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Order History','Istoric comenzi'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Order Id','ID-ul comenzii'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Order Information','Informații despre comandă'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Order note','Примечание заказа'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Order Status','Statutul comenzii'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Order summary','Rezumatul comenzii'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Order Total','Total');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','OrderId','ID-ul comenzii');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Orders','Comenzi'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Out Of Stock','Nu este disponibil');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Pages','Pagini'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Parent Category','Categoria părinte');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Password','Parola');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Payment','Plată'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Payment Providers','Sisteme de plată');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Pending','În așteptare'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Pending review replies','În așteptarea răspunsurilor la comentarii'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Pending reviews','Recenzii în așteptare'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Percent of product price discount','Procentul de reducere a produsului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Phone','Telefon'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Phone Number','Telefon'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Postal Code','Cod poștal'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Posted by','Autor');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Preview','Vizualizare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Price','Preț'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Process to Checkout','Procesul de finalizare a comenzii');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product','Produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Attribute','Atributele produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Attribute Groups','Grupuri de atribute de produse'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Attributes','Atributele produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product detail','Detalii produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Documents','Documentația produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Images','Imagini de produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Information','Informații despre produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Name','Denumirea produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Options','Opțiuni de produs'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Price Management','Managementul prețului produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Prices','Prețuri'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Sku','Sku produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product specification','Specificația produsului'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Templates','Șabloane de produse'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Product Variations','Opțiuni de produs');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Products','Produse'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','products in your cart','obiecte din coș'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Products Selection','Produse selectate');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Promotions','Promoții'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Publish End','Publicat pîna la'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Publish Start','Publicat de la');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Quantity','Cantitate');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Rate','Rată'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Rate this product','Evaluați acest produs');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Rating','Evaluare'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Rating average','Rata medie'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Recently viewed products','Produse recent vizualizate'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','records found','înregistrări găsite');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Register','Înregistrează-te');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Register as a new user?','Înregistrați-vă ca utilizator nou?'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Related Products','Produse similare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Remember me?','Ține-mă minte?');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Reply','Răspuns'); 
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Require coupon code','Codul cuponului este obligatoriu');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','results','rezultate');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Review comment','Text de recenzie');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Review Replies','Vizualizați recenziile');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Review title','Titlul recenziei');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Reviews','Recenzii');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Roles','Roluri');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Rule Name','Numele regulii');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Sales','Vânzări');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Save','Salvați');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Search here...','Caută aici...');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Security','Securitate');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Select culture','Alegerea limbii');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Select products to apply or leave blank for all products','Selectați produsele de aplicat sau lăsați necompletat pentru toate produsele');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Set as default shipping address','Setați ca adresă de expediere implicită');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Settings','Setări');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Shipment Id','Codul expedierii');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Shipments','Expedieri');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Shipping','Livrare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Shipping address','Adresă de livrare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Shipping Information','Informații despre livrare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Shipping methods','Metode de livrare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Shipping Providers','Furnizori de servicii de livrare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Shopping Cart','Coş');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Short content','Conținut scurt');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Short Description','Rezumat');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Site','Website');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Sort by:','Filtrează după:');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Special Price','Preț special');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Special Price End','Preț special pîna la');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Special Price Start','Preț special de la');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Specification','Specificație');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','stars','asteriscuri');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Start','Start');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','State Or Province','Regiune sau district');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','States or Provinces','Regiuni sau districte');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Status','Statut');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Stock History','Istoric stoc');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Stock management','Managementul inventarului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Stock management for warehouse','Gestionarea stocurilor pentru un depozit');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Stock Quantity','Cantitate în stoc');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Stocks','Stocuri');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Submit','Trimite');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Submit comment','Trimite comentariu');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Submit review','Postează o recenzie');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Submiting review is only enable for users who have bought this product','Trimiterea de feedback este disponibilă numai utilizatorilor care au achiziționat acest produs');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Subtotal','Subtotal');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','System','Sistem');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Tax Class','Clasa fiscală');;
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Clase de impozitare','Налоговые группы');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Tax Rates','Cotele de impozitare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Tax.DefaultTaxClassId','Grup fiscal implicit');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Thank you {0} for your review','Vă mulțumim {0} pentru feedback.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The {0} field is not a valid e-mail address.','Câmpul {0} nu este o adresă de e-mail validă.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The {0} field is required.','26/5000 Câmpul {0} este obligatoriu.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The {0} must be at least {2} and at max {1} characters long.','{0} trebuie să aibă cel puțin {2} și nu mai mult de {1} caractere.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The Email field is not a valid e-mail address.','Câmpul E-mail nu este o adresă de e-mail validă.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The Email field is required.','Câmpul E-mail este obligatoriu.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The new password and confirmation password do not match.','Parola nouă și parola de confirmare nu se potrivesc.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The page you have requested cannot be found','Pagina solicitată nu a fost găsită');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The password and confirmation password do not match.','Parola și confirmarea parolei nu se potrivesc.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The product has been added to your cart','Acest produs a fost adăugat în coș');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The supplied value is invalid for {0}.','Указанное значение недопустимо для {0}.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The value {0} is invalid.','25/5000 Valoarea {0} este nevalidă.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','The value {0} is not valid for {1}.','Valoarea {0} este nevalidă pentru {1}.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Themes','Teme');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','There are currently no items in your wish list.','Momentan nu există articole în lista de dorințe.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','There are no items in this cart.','Nu există articole în coș');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Thumbnail','Miniatură');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Title','Titlu');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','To','Pina la');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Tracking Number','Număr de urmărire');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Translations','Localizare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Type','Tip');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Usage limit per coupon','Limita de utilizare a cuponului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Usage limit per customer','Limita de utilizare per client');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Use','Utilizați');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Use a local account to log in.','Folosiți un cont local pentru a vă autentifica.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Use another service to log in.','Folosiți un alt serviciu pentru a vă conecta.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Use Selected Shipping Address As Billing Address','Utilizați adresa de expediere selectată ca adresă de facturare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','User List','listă de utilizatori');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Users','Utilizatori');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Value','Valoare');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','VAT included','TVA inclus');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Vendor Name','Numele furnizorului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Vendors','vânzători');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','View cart','Vizualizare coș');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','View History','Vezi istoricul');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','View Online Themes','Vizualizare online a temelor');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','View options','Vizualizați opțiunile');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Warehouse','Depozit');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Warehouses','Managementul depozitului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','We are sorry!','Ne pare foarte rău!');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Why not try and find your way using the navigation bar above or click on the logo to return our home page.','De ce nu încercați să găsiți drumul folosind bara de navigare de mai sus sau click pe logo-ul pentru a reveni la pagina noastră.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Widget Instances','Instanțe de widgeturi');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Widget Name','Numele widgetului');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Widget Type','Tipul de widget');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Widget Zone','Zona widget');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Widgets','Widgeturi');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Wish List','Listă de dorințe');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Yes','Da');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','You dot have any default address','Nu aveți o adresă implicită');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','You have','Voi aveti');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','You save','Ai economisit');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Your account','Contul Dvs');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Your comment','Comentariul Dvs');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Your comment should not have personal information. 10 - 300 characters:','Comentariul dvs. nu trebuie să conțină informații personale. 10 - 300 de caractere:');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Your review will be showed within the next 24h.','Recenzia dvs. va fi afișată în următoarele 24 de ore.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Your review will be shown within the next 24h.','Recenzia dvs. va fi publicată în următoarele 24 de ore.');
INSERT INTO public."Localization_Resource" ("CultureId", "Key", "Value") VALUES ('ro-RO','Zip Code','Cod postal');
