CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "ActivityLog_ActivityType" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    CONSTRAINT "PK_ActivityLog_ActivityType" PRIMARY KEY ("Id")
);

CREATE TABLE "Catalog_Brand" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "Slug" character varying(450) NOT NULL,
    "Description" text,
    "IsPublished" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Catalog_Brand" PRIMARY KEY ("Id")
);

CREATE TABLE "Catalog_ProductAttributeGroup" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    CONSTRAINT "PK_Catalog_ProductAttributeGroup" PRIMARY KEY ("Id")
);

CREATE TABLE "Catalog_ProductOption" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    CONSTRAINT "PK_Catalog_ProductOption" PRIMARY KEY ("Id")
);

CREATE TABLE "Catalog_ProductTemplate" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    CONSTRAINT "PK_Catalog_ProductTemplate" PRIMARY KEY ("Id")
);

CREATE TABLE "Cms_Menu" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "IsPublished" boolean NOT NULL,
    "IsSystem" boolean NOT NULL,
    CONSTRAINT "PK_Cms_Menu" PRIMARY KEY ("Id")
);

CREATE TABLE "Contacts_ContactArea" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Contacts_ContactArea" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Core_AppSetting" (
    "Id" text NOT NULL,
    "Value" character varying(450),
    "Module" character varying(450),
    "Key" text NULL,
    "IsVisibleInCommonSettingPage" boolean NOT NULL,
    CONSTRAINT "PK_Core_AppSetting" PRIMARY KEY ("Id")
);

CREATE TABLE "Core_Country" (
    "Id" text NOT NULL,
    "Name" character varying(450) NOT NULL,
    "Code3" character varying(450),
    "IsBillingEnabled" boolean NOT NULL,
    "IsShippingEnabled" boolean NOT NULL,
    "IsCityEnabled" boolean NOT NULL,
    "IsZipCodeEnabled" boolean NOT NULL,
    "IsDistrictEnabled" boolean NOT NULL,
    CONSTRAINT "PK_Core_Country" PRIMARY KEY ("Id")
);

CREATE TABLE "Core_CustomerGroup" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Core_CustomerGroup" PRIMARY KEY ("Id")
);

CREATE TABLE "Core_EntityType" (
    "Id" text NOT NULL,
    "IsMenuable" boolean NOT NULL,
    "AreaName" character varying(450),
    "RoutingController" character varying(450),
    "RoutingAction" character varying(450),
    CONSTRAINT "PK_Core_EntityType" PRIMARY KEY ("Id")
);

CREATE TABLE "Core_Media" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Caption" character varying(450),
    "FileSize" integer NOT NULL,
    "FileName" character varying(450),
    "MediaType" integer NOT NULL,
    CONSTRAINT "PK_Core_Media" PRIMARY KEY ("Id")
);

CREATE TABLE "Core_Role" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Core_Role" PRIMARY KEY ("Id")
);

CREATE TABLE "Core_Vendor" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "Slug" character varying(450) NOT NULL,
    "Description" text,
    "Email" text,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Core_Vendor" PRIMARY KEY ("Id")
);

CREATE TABLE "Core_Widget" (
    "Id" text NOT NULL,
    "Name" character varying(450) NOT NULL,
    "ViewComponentName" character varying(450),
    "CreateUrl" character varying(450),
    "EditUrl" character varying(450),
    "CreatedOn" timestamp with time zone NOT NULL,
    "IsPublished" boolean NOT NULL,
    CONSTRAINT "PK_Core_Widget" PRIMARY KEY ("Id")
);

CREATE TABLE "Core_WidgetZone" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "Description" text,
    CONSTRAINT "PK_Core_WidgetZone" PRIMARY KEY ("Id")
);

CREATE TABLE "Inventory_ProductBackInStockSubscription" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" bigint NOT NULL,
    "CustomerEmail" text,
    CONSTRAINT "PK_Inventory_ProductBackInStockSubscription" PRIMARY KEY ("Id")
);

CREATE TABLE "Localization_Culture" (
    "Id" text NOT NULL,
    "Name" character varying(450) NOT NULL,
    CONSTRAINT "PK_Localization_Culture" PRIMARY KEY ("Id")
);

CREATE TABLE "News_NewsCategory" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "Slug" character varying(450) NOT NULL,
    "MetaTitle" character varying(450),
    "MetaKeywords" character varying(450),
    "MetaDescription" text,
    "Description" text,
    "DisplayOrder" integer NOT NULL,
    "IsPublished" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_News_NewsCategory" PRIMARY KEY ("Id")
);

CREATE TABLE "Payments_PaymentProvider" (
    "Id" text NOT NULL,
    "Name" character varying(450) NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "ConfigureUrl" character varying(450),
    "LandingViewComponentName" character varying(450),
    "AdditionalSettings" text,
    CONSTRAINT "PK_Payments_PaymentProvider" PRIMARY KEY ("Id")
);

CREATE TABLE "Pricing_CartRule" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "StartOn" timestamp with time zone,
    "EndOn" timestamp with time zone,
    "IsCouponRequired" boolean NOT NULL,
    "RuleToApply" character varying(450),
    "DiscountAmount" numeric NOT NULL,
    "MaxDiscountAmount" numeric,
    "DiscountStep" integer,
    "UsageLimitPerCoupon" integer,
    "UsageLimitPerCustomer" integer,
    CONSTRAINT "PK_Pricing_CartRule" PRIMARY KEY ("Id")
);

CREATE TABLE "Pricing_CatalogRule" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "StartOn" timestamp with time zone,
    "EndOn" timestamp with time zone,
    "RuleToApply" character varying(450),
    "DiscountAmount" numeric NOT NULL,
    "MaxDiscountAmount" numeric,
    CONSTRAINT "PK_Pricing_CatalogRule" PRIMARY KEY ("Id")
);

CREATE TABLE "ProductRecentlyViewed_RecentlyViewedProduct" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ProductId" bigint NOT NULL,
    "LatestViewedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ProductRecentlyViewed_RecentlyViewedProduct" PRIMARY KEY ("Id")
);

CREATE TABLE "Search_Query" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "QueryText" character varying(500) NOT NULL,
    "ResultsCount" integer NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Search_Query" PRIMARY KEY ("Id")
);

CREATE TABLE "Shipping_ShippingProvider" (
    "Id" text NOT NULL,
    "Name" character varying(450) NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "ConfigureUrl" character varying(450),
    "ToAllShippingEnabledCountries" boolean NOT NULL,
    "OnlyCountryIdsString" character varying(1000),
    "ToAllShippingEnabledStatesOrProvinces" boolean NOT NULL,
    "OnlyStateOrProvinceIdsString" character varying(1000),
    "AdditionalSettings" text,
    "ShippingPriceServiceTypeName" character varying(450),
    CONSTRAINT "PK_Shipping_ShippingProvider" PRIMARY KEY ("Id")
);

CREATE TABLE "Tax_TaxClass" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    CONSTRAINT "PK_Tax_TaxClass" PRIMARY KEY ("Id")
);

CREATE TABLE "ActivityLog_Activity" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ActivityTypeId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "EntityId" bigint NOT NULL,
    "EntityTypeId" character varying(450) NOT NULL,
    CONSTRAINT "PK_ActivityLog_Activity" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ActivityLog_Activity_ActivityLog_ActivityType_ActivityTypeId" FOREIGN KEY ("ActivityTypeId") REFERENCES "ActivityLog_ActivityType" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Catalog_ProductAttribute" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "GroupId" bigint NOT NULL,
    CONSTRAINT "PK_Catalog_ProductAttribute" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catalog_ProductAttribute_Catalog_ProductAttributeGroup_Grou~" FOREIGN KEY ("GroupId") REFERENCES "Catalog_ProductAttributeGroup" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Contacts_Contact" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(450),
    "PhoneNumber" character varying(450),
    "EmailAddress" character varying(450),
    "Address" character varying(450),
    "Content" text,
    "ContactAreaId" bigint NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Contacts_Contact" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Contacts_Contact_Contacts_ContactArea_ContactAreaId" FOREIGN KEY ("ContactAreaId") REFERENCES "Contacts_ContactArea" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Core_StateOrProvince" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CountryId" character varying(450),
    "Code" character varying(450),
    "Name" character varying(450) NOT NULL,
    "Type" character varying(450),
    CONSTRAINT "PK_Core_StateOrProvince" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Core_StateOrProvince_Core_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Core_Country" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Core_Entity" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Slug" character varying(450) NOT NULL,
    "Name" character varying(450) NOT NULL,
    "EntityId" bigint NOT NULL,
    "EntityTypeId" character varying(450),
    CONSTRAINT "PK_Core_Entity" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Core_Entity_Core_EntityType_EntityTypeId" FOREIGN KEY ("EntityTypeId") REFERENCES "Core_EntityType" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Catalog_Category" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "Slug" character varying(450) NOT NULL,
    "MetaTitle" character varying(450),
    "MetaKeywords" character varying(450),
    "MetaDescription" text,
    "Description" text,
    "DisplayOrder" integer NOT NULL,
    "IsPublished" boolean NOT NULL,
    "IncludeInMenu" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ParentId" bigint,
    "ThumbnailImageId" bigint,
    CONSTRAINT "PK_Catalog_Category" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catalog_Category_Catalog_Category_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Catalog_Category" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Catalog_Category_Core_Media_ThumbnailImageId" FOREIGN KEY ("ThumbnailImageId") REFERENCES "Core_Media" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Core_RoleClaim" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" bigint NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_Core_RoleClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Core_RoleClaim_Core_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Core_Role" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Core_WidgetInstance" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450),
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    "PublishStart" timestamp with time zone,
    "PublishEnd" timestamp with time zone,
    "WidgetId" character varying(450),
    "WidgetZoneId" bigint NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "Data" text,
    "HtmlData" text,
    CONSTRAINT "PK_Core_WidgetInstance" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Core_WidgetInstance_Core_WidgetZone_WidgetZoneId" FOREIGN KEY ("WidgetZoneId") REFERENCES "Core_WidgetZone" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Core_WidgetInstance_Core_Widget_WidgetId" FOREIGN KEY ("WidgetId") REFERENCES "Core_Widget" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Localization_LocalizedContentProperty" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EntityId" bigint NOT NULL,
    "EntityType" character varying(450),
    "CultureId" text NOT NULL,
    "ProperyName" character varying(450) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_Localization_LocalizedContentProperty" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Localization_LocalizedContentProperty_Localization_Culture_~" FOREIGN KEY ("CultureId") REFERENCES "Localization_Culture" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Localization_Resource" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(450) NOT NULL,
    "Value" text,
    "CultureId" text NOT NULL,
    CONSTRAINT "PK_Localization_Resource" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Localization_Resource_Localization_Culture_CultureId" FOREIGN KEY ("CultureId") REFERENCES "Localization_Culture" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Pricing_CartRuleCustomerGroup" (
    "CartRuleId" bigint NOT NULL,
    "CustomerGroupId" bigint NOT NULL,
    CONSTRAINT "PK_Pricing_CartRuleCustomerGroup" PRIMARY KEY ("CartRuleId", "CustomerGroupId"),
    CONSTRAINT "FK_Pricing_CartRuleCustomerGroup_Core_CustomerGroup_CustomerGr~" FOREIGN KEY ("CustomerGroupId") REFERENCES "Core_CustomerGroup" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Pricing_CartRuleCustomerGroup_Pricing_CartRule_CartRuleId" FOREIGN KEY ("CartRuleId") REFERENCES "Pricing_CartRule" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Pricing_Coupon" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CartRuleId" bigint NOT NULL,
    "Code" character varying(450) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Pricing_Coupon" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Pricing_Coupon_Pricing_CartRule_CartRuleId" FOREIGN KEY ("CartRuleId") REFERENCES "Pricing_CartRule" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Pricing_CatalogRuleCustomerGroup" (
    "CatalogRuleId" bigint NOT NULL,
    "CustomerGroupId" bigint NOT NULL,
    CONSTRAINT "PK_Pricing_CatalogRuleCustomerGroup" PRIMARY KEY ("CatalogRuleId", "CustomerGroupId"),
    CONSTRAINT "FK_Pricing_CatalogRuleCustomerGroup_Core_CustomerGroup_Custome~" FOREIGN KEY ("CustomerGroupId") REFERENCES "Core_CustomerGroup" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Pricing_CatalogRuleCustomerGroup_Pricing_CatalogRule_Catalo~" FOREIGN KEY ("CatalogRuleId") REFERENCES "Pricing_CatalogRule" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Catalog_ProductTemplateProductAttribute" (
    "ProductTemplateId" bigint NOT NULL,
    "ProductAttributeId" bigint NOT NULL,
    CONSTRAINT "PK_Catalog_ProductTemplateProductAttribute" PRIMARY KEY ("ProductTemplateId", "ProductAttributeId"),
    CONSTRAINT "FK_Catalog_ProductTemplateProductAttribute_Catalog_ProductAttr~" FOREIGN KEY ("ProductAttributeId") REFERENCES "Catalog_ProductAttribute" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Catalog_ProductTemplateProductAttribute_Catalog_ProductTemp~" FOREIGN KEY ("ProductTemplateId") REFERENCES "Catalog_ProductTemplate" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Core_District" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StateOrProvinceId" bigint NOT NULL,
    "Name" character varying(450) NOT NULL,
    "Type" character varying(450),
    "Location" text,
    CONSTRAINT "PK_Core_District" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Core_District_Core_StateOrProvince_StateOrProvinceId" FOREIGN KEY ("StateOrProvinceId") REFERENCES "Core_StateOrProvince" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Tax_TaxRate" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaxClassId" bigint NOT NULL,
    "CountryId" character varying(450),
    "StateOrProvinceId" bigint,
    "Rate" numeric NOT NULL,
    "ZipCode" character varying(450),
    CONSTRAINT "PK_Tax_TaxRate" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Tax_TaxRate_Core_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Core_Country" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Tax_TaxRate_Core_StateOrProvince_StateOrProvinceId" FOREIGN KEY ("StateOrProvinceId") REFERENCES "Core_StateOrProvince" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Tax_TaxRate_Tax_TaxClass_TaxClassId" FOREIGN KEY ("TaxClassId") REFERENCES "Tax_TaxClass" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Cms_MenuItem" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ParentId" bigint,
    "MenuId" bigint NOT NULL,
    "EntityId" bigint,
    "CustomLink" character varying(450),
    "Name" character varying(450),
    "DisplayOrder" integer NOT NULL,
    CONSTRAINT "PK_Cms_MenuItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cms_MenuItem_Cms_MenuItem_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Cms_MenuItem" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Cms_MenuItem_Cms_Menu_MenuId" FOREIGN KEY ("MenuId") REFERENCES "Cms_Menu" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Cms_MenuItem_Core_Entity_EntityId" FOREIGN KEY ("EntityId") REFERENCES "Core_Entity" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Pricing_CartRuleCategory" (
    "CategoryId" bigint NOT NULL,
    "CartRuleId" bigint NOT NULL,
    CONSTRAINT "PK_Pricing_CartRuleCategory" PRIMARY KEY ("CartRuleId", "CategoryId"),
    CONSTRAINT "FK_Pricing_CartRuleCategory_Catalog_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Catalog_Category" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Pricing_CartRuleCategory_Pricing_CartRule_CartRuleId" FOREIGN KEY ("CartRuleId") REFERENCES "Pricing_CartRule" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Core_Address" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ContactName" character varying(450),
    "Phone" character varying(450),
    "AddressLine1" character varying(450),
    "AddressLine2" character varying(450),
    "City" character varying(450),
    "ZipCode" character varying(450),
    "DistrictId" bigint,
    "StateOrProvinceId" bigint NOT NULL,
    "CountryId" character varying(450) NOT NULL,
    CONSTRAINT "PK_Core_Address" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Core_Address_Core_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Core_Country" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Core_Address_Core_District_DistrictId" FOREIGN KEY ("DistrictId") REFERENCES "Core_District" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Core_Address_Core_StateOrProvince_StateOrProvinceId" FOREIGN KEY ("StateOrProvinceId") REFERENCES "Core_StateOrProvince" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Orders_OrderAddress" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ContactName" character varying(450),
    "Phone" character varying(450),
    "AddressLine1" character varying(450),
    "AddressLine2" character varying(450),
    "City" character varying(450),
    "ZipCode" character varying(450),
    "DistrictId" bigint,
    "StateOrProvinceId" bigint NOT NULL,
    "CountryId" character varying(450),
    CONSTRAINT "PK_Orders_OrderAddress" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_OrderAddress_Core_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Core_Country" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_OrderAddress_Core_District_DistrictId" FOREIGN KEY ("DistrictId") REFERENCES "Core_District" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_OrderAddress_Core_StateOrProvince_StateOrProvinceId" FOREIGN KEY ("StateOrProvinceId") REFERENCES "Core_StateOrProvince" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ShippingTableRate_PriceAndDestination" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CountryId" character varying(450),
    "StateOrProvinceId" bigint,
    "DistrictId" bigint,
    "ZipCode" character varying(450),
    "Note" text,
    "MinOrderSubtotal" numeric NOT NULL,
    "ShippingPrice" numeric NOT NULL,
    CONSTRAINT "PK_ShippingTableRate_PriceAndDestination" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ShippingTableRate_PriceAndDestination_Core_Country_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Core_Country" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ShippingTableRate_PriceAndDestination_Core_District_Distric~" FOREIGN KEY ("DistrictId") REFERENCES "Core_District" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ShippingTableRate_PriceAndDestination_Core_StateOrProvince_~" FOREIGN KEY ("StateOrProvinceId") REFERENCES "Core_StateOrProvince" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Inventory_Warehouse" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(450) NOT NULL,
    "AddressId" bigint NOT NULL,
    "VendorId" bigint,
    CONSTRAINT "PK_Inventory_Warehouse" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Inventory_Warehouse_Core_Address_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Core_Address" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Inventory_Warehouse_Core_Vendor_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Core_Vendor" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Catalog_Product" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ShortDescription" character varying(450),
    "Description" text,
    "Specification" text,
    "Price" numeric NOT NULL,
    "OldPrice" numeric,
    "SpecialPrice" numeric,
    "SpecialPriceStart" timestamp with time zone,
    "SpecialPriceEnd" timestamp with time zone,
    "HasOptions" boolean NOT NULL,
    "IsVisibleIndividually" boolean NOT NULL,
    "IsFeatured" boolean NOT NULL,
    "IsCallForPricing" boolean NOT NULL,
    "IsAllowToOrder" boolean NOT NULL,
    "StockTrackingIsEnabled" boolean NOT NULL,
    "StockQuantity" integer NOT NULL,
    "Sku" character varying(450),
    "Gtin" character varying(450),
    "NormalizedName" character varying(450),
    "DisplayOrder" integer NOT NULL,
    "VendorId" bigint,
    "ThumbnailImageId" bigint,
    "ReviewsCount" integer NOT NULL,
    "RatingAverage" double precision,
    "BrandId" bigint,
    "TaxClassId" bigint,
    "Name" character varying(450) NOT NULL,
    "Slug" character varying(450) NOT NULL,
    "MetaTitle" character varying(450),
    "MetaKeywords" character varying(450),
    "MetaDescription" text,
    "IsPublished" boolean NOT NULL,
    "PublishedOn" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedById" bigint NOT NULL,
    CONSTRAINT "PK_Catalog_Product" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catalog_Product_Catalog_Brand_BrandId" FOREIGN KEY ("BrandId") REFERENCES "Catalog_Brand" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Catalog_Product_Core_Media_ThumbnailImageId" FOREIGN KEY ("ThumbnailImageId") REFERENCES "Core_Media" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Catalog_Product_Tax_TaxClass_TaxClassId" FOREIGN KEY ("TaxClassId") REFERENCES "Tax_TaxClass" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Catalog_ProductAttributeValue" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AttributeId" bigint NOT NULL,
    "ProductId" bigint NOT NULL,
    "Value" text,
    CONSTRAINT "PK_Catalog_ProductAttributeValue" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catalog_ProductAttributeValue_Catalog_ProductAttribute_Attr~" FOREIGN KEY ("AttributeId") REFERENCES "Catalog_ProductAttribute" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Catalog_ProductAttributeValue_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Catalog_ProductCategory" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IsFeaturedProduct" boolean NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "CategoryId" bigint NOT NULL,
    "ProductId" bigint NOT NULL,
    CONSTRAINT "PK_Catalog_ProductCategory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catalog_ProductCategory_Catalog_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Catalog_Category" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Catalog_ProductCategory_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Catalog_ProductLink" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" bigint NOT NULL,
    "LinkedProductId" bigint NOT NULL,
    "LinkType" integer NOT NULL,
    CONSTRAINT "PK_Catalog_ProductLink" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catalog_ProductLink_Catalog_Product_LinkedProductId" FOREIGN KEY ("LinkedProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Catalog_ProductLink_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Catalog_ProductMedia" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" bigint NOT NULL,
    "MediaId" bigint NOT NULL,
    "DisplayOrder" integer NOT NULL,
    CONSTRAINT "PK_Catalog_ProductMedia" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catalog_ProductMedia_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Catalog_ProductMedia_Core_Media_MediaId" FOREIGN KEY ("MediaId") REFERENCES "Core_Media" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Catalog_ProductOptionCombination" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" bigint NOT NULL,
    "OptionId" bigint NOT NULL,
    "Value" character varying(450),
    "SortIndex" integer NOT NULL,
    CONSTRAINT "PK_Catalog_ProductOptionCombination" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catalog_ProductOptionCombination_Catalog_ProductOption_Opti~" FOREIGN KEY ("OptionId") REFERENCES "Catalog_ProductOption" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Catalog_ProductOptionCombination_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Catalog_ProductOptionValue" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OptionId" bigint NOT NULL,
    "ProductId" bigint NOT NULL,
    "Value" character varying(450),
    "DisplayType" character varying(450),
    "SortIndex" integer NOT NULL,
    CONSTRAINT "PK_Catalog_ProductOptionValue" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catalog_ProductOptionValue_Catalog_ProductOption_OptionId" FOREIGN KEY ("OptionId") REFERENCES "Catalog_ProductOption" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Catalog_ProductOptionValue_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Inventory_Stock" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" bigint NOT NULL,
    "WarehouseId" bigint NOT NULL,
    "Quantity" integer NOT NULL,
    "ReservedQuantity" integer NOT NULL,
    CONSTRAINT "PK_Inventory_Stock" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Inventory_Stock_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Inventory_Stock_Inventory_Warehouse_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Inventory_Warehouse" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Pricing_CartRuleProduct" (
    "ProductId" bigint NOT NULL,
    "CartRuleId" bigint NOT NULL,
    CONSTRAINT "PK_Pricing_CartRuleProduct" PRIMARY KEY ("CartRuleId", "ProductId"),
    CONSTRAINT "FK_Pricing_CartRuleProduct_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Pricing_CartRuleProduct_Pricing_CartRule_CartRuleId" FOREIGN KEY ("CartRuleId") REFERENCES "Pricing_CartRule" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Catalog_ProductPriceHistory" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" bigint,
    "CreatedById" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "Price" numeric,
    "OldPrice" numeric,
    "SpecialPrice" numeric,
    "SpecialPriceStart" timestamp with time zone,
    "SpecialPriceEnd" timestamp with time zone,
    CONSTRAINT "PK_Catalog_ProductPriceHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catalog_ProductPriceHistory_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Checkouts_Checkout" (
    "Id" uuid NOT NULL,
    "CustomerId" bigint NOT NULL,
    "CreatedById" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    "CouponCode" character varying(450),
    "CouponRuleName" character varying(450),
    "ShippingMethod" character varying(450),
    "IsProductPriceIncludeTax" boolean NOT NULL,
    "ShippingAmount" numeric,
    "TaxAmount" numeric,
    "VendorId" bigint,
    "ShippingData" text,
    "OrderNote" character varying(1000),
    CONSTRAINT "PK_Checkouts_Checkout" PRIMARY KEY ("Id")
);

CREATE TABLE "Checkouts_CheckoutItem" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CreatedOn" timestamp with time zone NOT NULL,
    "ProductId" bigint NOT NULL,
    "Quantity" integer NOT NULL,
    "CheckoutId" uuid NOT NULL,
    CONSTRAINT "PK_Checkouts_CheckoutItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Checkouts_CheckoutItem_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Checkouts_CheckoutItem_Checkouts_Checkout_CheckoutId" FOREIGN KEY ("CheckoutId") REFERENCES "Checkouts_Checkout" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Cms_Page" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Body" text,
    "Name" character varying(450) NOT NULL,
    "Slug" character varying(450) NOT NULL,
    "MetaTitle" character varying(450),
    "MetaKeywords" character varying(450),
    "MetaDescription" text,
    "IsPublished" boolean NOT NULL,
    "PublishedOn" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedById" bigint NOT NULL,
    CONSTRAINT "PK_Cms_Page" PRIMARY KEY ("Id")
);

CREATE TABLE "Comments_Comment" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "CommentText" text,
    "CommenterName" character varying(450),
    "Status" integer NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "EntityTypeId" character varying(450),
    "EntityId" bigint NOT NULL,
    "ParentId" bigint,
    CONSTRAINT "PK_Comments_Comment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Comment_Comments_Comment_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Comments_Comment" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Core_CustomerGroupUser" (
    "UserId" bigint NOT NULL,
    "CustomerGroupId" bigint NOT NULL,
    CONSTRAINT "PK_Core_CustomerGroupUser" PRIMARY KEY ("UserId", "CustomerGroupId"),
    CONSTRAINT "FK_Core_CustomerGroupUser_Core_CustomerGroup_CustomerGroupId" FOREIGN KEY ("CustomerGroupId") REFERENCES "Core_CustomerGroup" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Core_User" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserGuid" uuid NOT NULL,
    "FullName" character varying(450) NOT NULL,
    "VendorId" bigint,
    "IsDeleted" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    "DefaultShippingAddressId" bigint,
    "DefaultBillingAddressId" bigint,
    "RefreshTokenHash" character varying(450),
    "Culture" character varying(450),
    "ExtensionData" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Core_User" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Core_User_Core_Vendor_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Core_Vendor" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Core_UserAddress" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "AddressId" bigint NOT NULL,
    "AddressType" integer NOT NULL,
    "LastUsedOn" timestamp with time zone,
    CONSTRAINT "PK_Core_UserAddress" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Core_UserAddress_Core_Address_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Core_Address" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Core_UserAddress_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Core_UserClaim" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_Core_UserClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Core_UserClaim_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Core_UserLogin" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" bigint NOT NULL,
    CONSTRAINT "PK_Core_UserLogin" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_Core_UserLogin_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Core_UserRole" (
    "UserId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    CONSTRAINT "PK_Core_UserRole" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_Core_UserRole_Core_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Core_Role" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Core_UserRole_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Core_UserToken" (
    "UserId" bigint NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_Core_UserToken" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_Core_UserToken_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Inventory_StockHistory" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" bigint NOT NULL,
    "WarehouseId" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedById" bigint NOT NULL,
    "AdjustedQuantity" bigint NOT NULL,
    "Note" character varying(1000),
    CONSTRAINT "PK_Inventory_StockHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Inventory_StockHistory_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Inventory_StockHistory_Core_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Inventory_StockHistory_Inventory_Warehouse_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Inventory_Warehouse" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "News_NewsItem" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ShortContent" character varying(450),
    "FullContent" text,
    "ThumbnailImageId" bigint,
    "Name" character varying(450) NOT NULL,
    "Slug" character varying(450) NOT NULL,
    "MetaTitle" character varying(450),
    "MetaKeywords" character varying(450),
    "MetaDescription" text,
    "IsPublished" boolean NOT NULL,
    "PublishedOn" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedById" bigint NOT NULL,
    CONSTRAINT "PK_News_NewsItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_News_NewsItem_Core_Media_ThumbnailImageId" FOREIGN KEY ("ThumbnailImageId") REFERENCES "Core_Media" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_News_NewsItem_Core_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_News_NewsItem_Core_User_LatestUpdatedById" FOREIGN KEY ("LatestUpdatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Orders_Order" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CustomerId" bigint NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedById" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedById" bigint NOT NULL,
    "VendorId" bigint,
    "CouponCode" character varying(450),
    "CouponRuleName" character varying(450),
    "DiscountAmount" numeric NOT NULL,
    "SubTotal" numeric NOT NULL,
    "SubTotalWithDiscount" numeric NOT NULL,
    "ShippingAddressId" bigint NOT NULL,
    "BillingAddressId" bigint NOT NULL,
    "OrderStatus" integer NOT NULL,
    "OrderNote" character varying(1000),
    "ParentId" bigint,
    "IsMasterOrder" boolean NOT NULL,
    "ShippingMethod" character varying(450),
    "ShippingFeeAmount" numeric NOT NULL,
    "TaxAmount" numeric NOT NULL,
    "OrderTotal" numeric NOT NULL,
    "PaymentMethod" character varying(450),
    "PaymentFeeAmount" numeric NOT NULL,
    CONSTRAINT "PK_Orders_Order" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Order_Core_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Order_Core_User_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Order_Core_User_LatestUpdatedById" FOREIGN KEY ("LatestUpdatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Order_Orders_OrderAddress_BillingAddressId" FOREIGN KEY ("BillingAddressId") REFERENCES "Orders_OrderAddress" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Order_Orders_OrderAddress_ShippingAddressId" FOREIGN KEY ("ShippingAddressId") REFERENCES "Orders_OrderAddress" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Order_Orders_Order_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Orders_Order" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Pricing_CartRuleUsage" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CartRuleId" bigint NOT NULL,
    "CouponId" bigint,
    "UserId" bigint NOT NULL,
    "OrderId" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Pricing_CartRuleUsage" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Pricing_CartRuleUsage_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Pricing_CartRuleUsage_Pricing_CartRule_CartRuleId" FOREIGN KEY ("CartRuleId") REFERENCES "Pricing_CartRule" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Pricing_CartRuleUsage_Pricing_Coupon_CouponId" FOREIGN KEY ("CouponId") REFERENCES "Pricing_Coupon" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ProductComparison_ComparingProduct" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UserId" bigint NOT NULL,
    "ProductId" bigint NOT NULL,
    CONSTRAINT "PK_ProductComparison_ComparingProduct" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductComparison_ComparingProduct_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ProductComparison_ComparingProduct_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Reviews_Review" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "Title" character varying(450),
    "Comment" text,
    "Rating" integer NOT NULL,
    "ReviewerName" character varying(450),
    "Status" integer NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "EntityTypeId" character varying(450),
    "EntityId" bigint NOT NULL,
    CONSTRAINT "PK_Reviews_Review" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_Review_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ShoppingCart_CartItem" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    "ProductId" bigint NOT NULL,
    "Quantity" integer NOT NULL,
    "CustomerId" bigint NOT NULL,
    "VendorId" bigint,
    CONSTRAINT "PK_ShoppingCart_CartItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ShoppingCart_CartItem_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ShoppingCart_CartItem_Core_User_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "WishList_WishList" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "SharingCode" character varying(450),
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WishList_WishList" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WishList_WishList_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "News_NewsItemCategory" (
    "CategoryId" bigint NOT NULL,
    "NewsItemId" bigint NOT NULL,
    CONSTRAINT "PK_News_NewsItemCategory" PRIMARY KEY ("CategoryId", "NewsItemId"),
    CONSTRAINT "FK_News_NewsItemCategory_News_NewsCategory_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "News_NewsCategory" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_News_NewsItemCategory_News_NewsItem_NewsItemId" FOREIGN KEY ("NewsItemId") REFERENCES "News_NewsItem" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Orders_OrderHistory" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" bigint NOT NULL,
    "OldStatus" integer,
    "NewStatus" integer NOT NULL,
    "OrderSnapshot" text,
    "Note" character varying(1000),
    "CreatedOn" timestamp with time zone NOT NULL,
    "CreatedById" bigint NOT NULL,
    CONSTRAINT "PK_Orders_OrderHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_OrderHistory_Core_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_OrderHistory_Orders_Order_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders_Order" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Orders_OrderItem" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" bigint,
    "ProductId" bigint NOT NULL,
    "ProductPrice" numeric NOT NULL,
    "Quantity" integer NOT NULL,
    "DiscountAmount" numeric NOT NULL,
    "TaxAmount" numeric NOT NULL,
    "TaxPercent" numeric NOT NULL,
    CONSTRAINT "PK_Orders_OrderItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_OrderItem_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_OrderItem_Orders_Order_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders_Order" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Payments_Payment" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    "Amount" numeric NOT NULL,
    "PaymentFee" numeric NOT NULL,
    "PaymentMethod" character varying(450),
    "GatewayTransactionId" character varying(450),
    "Status" integer NOT NULL,
    "FailureMessage" text,
    CONSTRAINT "PK_Payments_Payment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Payment_Orders_Order_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders_Order" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Shipments_Shipment" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" bigint NOT NULL,
    "TrackingNumber" character varying(450),
    "WarehouseId" bigint NOT NULL,
    "VendorId" bigint,
    "CreatedById" bigint NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Shipments_Shipment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shipments_Shipment_Core_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Shipments_Shipment_Inventory_Warehouse_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Inventory_Warehouse" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Shipments_Shipment_Orders_Order_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders_Order" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Reviews_Reply" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ReviewId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "Comment" text,
    "ReplierName" character varying(450),
    "Status" integer NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews_Reply" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_Reply_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_Reply_Reviews_Review_ReviewId" FOREIGN KEY ("ReviewId") REFERENCES "Reviews_Review" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "WishList_WishListItem" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "WishListId" bigint NOT NULL,
    "ProductId" bigint NOT NULL,
    "Description" text,
    "Quantity" integer NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "LatestUpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WishList_WishListItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WishList_WishListItem_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_WishList_WishListItem_WishList_WishList_WishListId" FOREIGN KEY ("WishListId") REFERENCES "WishList_WishList" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Shipments_ShipmentItem" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ShipmentId" bigint NOT NULL,
    "OrderItemId" bigint NOT NULL,
    "ProductId" bigint NOT NULL,
    "Quantity" integer NOT NULL,
    CONSTRAINT "PK_Shipments_ShipmentItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shipments_ShipmentItem_Catalog_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Catalog_Product" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Shipments_ShipmentItem_Shipments_Shipment_ShipmentId" FOREIGN KEY ("ShipmentId") REFERENCES "Shipments_Shipment" ("Id") ON DELETE RESTRICT
);

INSERT INTO "ActivityLog_ActivityType" ("Id", "Name")
VALUES (1, 'EntityView');

INSERT INTO "Catalog_ProductOption" ("Id", "Name")
VALUES (1, 'Color');
INSERT INTO "Catalog_ProductOption" ("Id", "Name")
VALUES (2, 'Size');

INSERT INTO "Cms_Menu" ("Id", "IsPublished", "IsSystem", "Name")
VALUES (1, TRUE, TRUE, 'Customer Services');
INSERT INTO "Cms_Menu" ("Id", "IsPublished", "IsSystem", "Name")
VALUES (2, TRUE, TRUE, 'Information');

INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Catalog.IsCommentsRequireApproval', TRUE, 'Catalog', 'true');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Catalog.IsProductPriceIncludeTax', TRUE, 'Catalog', 'true');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Catalog.MinimumProductQuantityForHighlighting', TRUE, 'Catalog', '5');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Catalog.ProductPageSize', TRUE, 'Catalog', '10');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Global.AssetBundling', TRUE, 'Core', 'false');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Global.AssetVersion', TRUE, 'Core', '1.0');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Global.CurrencyCulture', TRUE, 'Core', 'en-US');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Global.CurrencyDecimalPlace', TRUE, 'Core', '2');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Global.DefaultCultureAdminUI', TRUE, 'Core', 'en-US');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Global.DefaultCultureUI', TRUE, 'Core', 'en-US');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('GoogleAppKey', FALSE, 'Contact', '');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Localization.LocalizedConentEnable', TRUE, 'Localization', 'true');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('News.PageSize', TRUE, 'News', '10');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('SmtpPassword', FALSE, 'EmailSenderSmpt', '');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('SmtpPort', FALSE, 'EmailSenderSmpt', '587');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('SmtpServer', FALSE, 'EmailSenderSmpt', 'smtp.gmail.com');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('SmtpUsername', FALSE, 'EmailSenderSmpt', '');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Tax.DefaultTaxClassId', TRUE, 'Tax', '1');
INSERT INTO "Core_AppSetting" ("Id", "IsVisibleInCommonSettingPage", "Module", "Value")
VALUES ('Theme', FALSE, 'Core', 'Generic');

INSERT INTO "Core_Country" ("Id", "Code3", "IsBillingEnabled", "IsCityEnabled", "IsDistrictEnabled", "IsShippingEnabled", "IsZipCodeEnabled", "Name")
VALUES ('US', 'USA', TRUE, TRUE, FALSE, TRUE, TRUE, 'United States');
INSERT INTO "Core_Country" ("Id", "Code3", "IsBillingEnabled", "IsCityEnabled", "IsDistrictEnabled", "IsShippingEnabled", "IsZipCodeEnabled", "Name")
VALUES ('VN', 'VNM', TRUE, FALSE, TRUE, TRUE, FALSE, 'Việt Nam');

INSERT INTO "Core_EntityType" ("Id", "AreaName", "IsMenuable", "RoutingAction", "RoutingController")
VALUES ('Brand', 'Catalog', TRUE, 'BrandDetail', 'Brand');
INSERT INTO "Core_EntityType" ("Id", "AreaName", "IsMenuable", "RoutingAction", "RoutingController")
VALUES ('Category', 'Catalog', TRUE, 'CategoryDetail', 'Category');
INSERT INTO "Core_EntityType" ("Id", "AreaName", "IsMenuable", "RoutingAction", "RoutingController")
VALUES ('NewsCategory', 'News', TRUE, 'NewsCategoryDetail', 'NewsCategory');
INSERT INTO "Core_EntityType" ("Id", "AreaName", "IsMenuable", "RoutingAction", "RoutingController")
VALUES ('NewsItem', 'News', FALSE, 'NewsItemDetail', 'NewsItem');
INSERT INTO "Core_EntityType" ("Id", "AreaName", "IsMenuable", "RoutingAction", "RoutingController")
VALUES ('Page', 'Cms', TRUE, 'PageDetail', 'Page');
INSERT INTO "Core_EntityType" ("Id", "AreaName", "IsMenuable", "RoutingAction", "RoutingController")
VALUES ('Product', 'Catalog', FALSE, 'ProductDetail', 'Product');
INSERT INTO "Core_EntityType" ("Id", "AreaName", "IsMenuable", "RoutingAction", "RoutingController")
VALUES ('Vendor', 'Core', FALSE, 'VendorDetail', 'Vendor');

INSERT INTO "Core_Role" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES (1, '4776a1b2-dbe4-4056-82ec-8bed211d1454', 'admin', 'ADMIN');
INSERT INTO "Core_Role" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES (2, '00d172be-03a0-4856-8b12-26d63fcf4374', 'customer', 'CUSTOMER');
INSERT INTO "Core_Role" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES (3, 'd4754388-8355-4018-b728-218018836817', 'guest', 'GUEST');
INSERT INTO "Core_Role" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES (4, '71f10604-8c4d-4a7d-ac4a-ffefb11cefeb', 'vendor', 'VENDOR');

INSERT INTO "Core_User" ("Id", "AccessFailedCount", "ConcurrencyStamp", "CreatedOn", "Culture", "DefaultBillingAddressId", "DefaultShippingAddressId", "Email", "EmailConfirmed", "ExtensionData", "FullName", "IsDeleted", "LatestUpdatedOn", "LockoutEnabled", "LockoutEnd", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "RefreshTokenHash", "SecurityStamp", "TwoFactorEnabled", "UserGuid", "UserName", "VendorId")
VALUES (2, 0, '101cd6ae-a8ef-4a37-97fd-04ac2dd630e4', TIMESTAMPTZ '2018-05-29T04:33:39.189+07:00', NULL, NULL, NULL, 'system@simplcommerce.com', FALSE, NULL, 'System User', TRUE, TIMESTAMPTZ '2018-05-29T04:33:39.189+07:00', FALSE, NULL, 'SYSTEM@SIMPLCOMMERCE.COM', 'SYSTEM@SIMPLCOMMERCE.COM', 'AQAAAAEAACcQAAAAEAEqSCV8Bpg69irmeg8N86U503jGEAYf75fBuzvL00/mr/FGEsiUqfR0rWBbBUwqtw==', NULL, FALSE, NULL, 'a9565acb-cee6-425f-9833-419a793f5fba', FALSE, '5f72f83b-7436-4221-869c-1b69b2e23aae', 'system@simplcommerce.com', NULL);
INSERT INTO "Core_User" ("Id", "AccessFailedCount", "ConcurrencyStamp", "CreatedOn", "Culture", "DefaultBillingAddressId", "DefaultShippingAddressId", "Email", "EmailConfirmed", "ExtensionData", "FullName", "IsDeleted", "LatestUpdatedOn", "LockoutEnabled", "LockoutEnd", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "RefreshTokenHash", "SecurityStamp", "TwoFactorEnabled", "UserGuid", "UserName", "VendorId")
VALUES (10, 0, 'c83afcbc-312c-4589-bad7-8686bd4754c0', TIMESTAMPTZ '2018-05-29T04:33:39.19+07:00', NULL, NULL, NULL, 'admin@simplcommerce.com', FALSE, NULL, 'Shop Admin', FALSE, TIMESTAMPTZ '2018-05-29T04:33:39.19+07:00', FALSE, NULL, 'ADMIN@SIMPLCOMMERCE.COM', 'ADMIN@SIMPLCOMMERCE.COM', 'AQAAAAEAACcQAAAAEAEqSCV8Bpg69irmeg8N86U503jGEAYf75fBuzvL00/mr/FGEsiUqfR0rWBbBUwqtw==', NULL, FALSE, NULL, 'd6847450-47f0-4c7a-9fed-0c66234bf61f', FALSE, 'ed8210c3-24b0-4823-a744-80078cf12eb4', 'admin@simplcommerce.com', NULL);

INSERT INTO "Core_Widget" ("Id", "CreateUrl", "CreatedOn", "EditUrl", "IsPublished", "Name", "ViewComponentName")
VALUES ('CarouselWidget', 'widget-carousel-create', TIMESTAMPTZ '2018-05-29T04:33:39.164+07:00', 'widget-carousel-edit', FALSE, 'Carousel Widget', 'CarouselWidget');
INSERT INTO "Core_Widget" ("Id", "CreateUrl", "CreatedOn", "EditUrl", "IsPublished", "Name", "ViewComponentName")
VALUES ('CategoryWidget', 'widget-category-create', TIMESTAMPTZ '2018-05-29T04:33:39.16+07:00', 'widget-category-edit', FALSE, 'Category Widget', 'CategoryWidget');
INSERT INTO "Core_Widget" ("Id", "CreateUrl", "CreatedOn", "EditUrl", "IsPublished", "Name", "ViewComponentName")
VALUES ('HtmlWidget', 'widget-html-create', TIMESTAMPTZ '2018-05-29T04:33:39.164+07:00', 'widget-html-edit', FALSE, 'Html Widget', 'HtmlWidget');
INSERT INTO "Core_Widget" ("Id", "CreateUrl", "CreatedOn", "EditUrl", "IsPublished", "Name", "ViewComponentName")
VALUES ('ProductWidget', 'widget-product-create', TIMESTAMPTZ '2018-05-29T04:33:39.163+07:00', 'widget-product-edit', FALSE, 'Product Widget', 'ProductWidget');
INSERT INTO "Core_Widget" ("Id", "CreateUrl", "CreatedOn", "EditUrl", "IsPublished", "Name", "ViewComponentName")
VALUES ('RecentlyViewedWidget', 'widget-recently-viewed-create', TIMESTAMPTZ '2018-05-29T04:33:39.164+07:00', 'widget-recently-viewed-edit', FALSE, 'Recently Viewed Widget', 'RecentlyViewedWidget');
INSERT INTO "Core_Widget" ("Id", "CreateUrl", "CreatedOn", "EditUrl", "IsPublished", "Name", "ViewComponentName")
VALUES ('SimpleProductWidget', 'widget-simple-product-create', TIMESTAMPTZ '2018-05-29T04:33:39.163+07:00', 'widget-simple-product-edit', FALSE, 'Simple Product Widget', 'SimpleProductWidget');
INSERT INTO "Core_Widget" ("Id", "CreateUrl", "CreatedOn", "EditUrl", "IsPublished", "Name", "ViewComponentName")
VALUES ('SpaceBarWidget', 'widget-spacebar-create', TIMESTAMPTZ '2018-05-29T04:33:39.164+07:00', 'widget-spacebar-edit', FALSE, 'SpaceBar Widget', 'SpaceBarWidget');

INSERT INTO "Core_WidgetZone" ("Id", "Description", "Name")
VALUES (1, NULL, 'Home Featured');
INSERT INTO "Core_WidgetZone" ("Id", "Description", "Name")
VALUES (2, NULL, 'Home Main Content');
INSERT INTO "Core_WidgetZone" ("Id", "Description", "Name")
VALUES (3, NULL, 'Home After Main Content');

INSERT INTO "Localization_Culture" ("Id", "Name")
VALUES ('en-US', 'English (US)');

INSERT INTO "Payments_PaymentProvider" ("Id", "AdditionalSettings", "ConfigureUrl", "IsEnabled", "LandingViewComponentName", "Name")
VALUES ('Braintree', '{"PublicKey": "6j4d7qspt5n48kx4", "PrivateKey" : "bd1c26e53a6d811243fcc3eb268113e1", "MerchantId" : "ncsh7wwqvzs3cx9q", "IsProduction" : "false"}', 'payments-braintree-config', TRUE, 'BraintreeLanding', 'Braintree');
INSERT INTO "Payments_PaymentProvider" ("Id", "AdditionalSettings", "ConfigureUrl", "IsEnabled", "LandingViewComponentName", "Name")
VALUES ('Cashfree', '{ "IsSandbox":true, "AppId":"358035b02486f36ca27904540853", "SecretKey":"26f48dcd6a27f89f59f28e65849e587916dd57b9" }', 'payments-cashfree-config', TRUE, 'CashfreeLanding', 'Cashfree Payment Gateway');
INSERT INTO "Payments_PaymentProvider" ("Id", "AdditionalSettings", "ConfigureUrl", "IsEnabled", "LandingViewComponentName", "Name")
VALUES ('CoD', NULL, 'payments-cod-config', TRUE, 'CoDLanding', 'Cash On Delivery');
INSERT INTO "Payments_PaymentProvider" ("Id", "AdditionalSettings", "ConfigureUrl", "IsEnabled", "LandingViewComponentName", "Name")
VALUES ('MomoPayment', '{"IsSandbox":true,"PartnerCode":"MOMOIQA420180417","AccessKey":"SvDmj2cOTYZmQQ3H","SecretKey":"PPuDXq1KowPT1ftR8DvlQTHhC03aul17","PaymentFee":0.0}', 'payments-momo-config', TRUE, 'MomoLanding', 'Momo Payment');
INSERT INTO "Payments_PaymentProvider" ("Id", "AdditionalSettings", "ConfigureUrl", "IsEnabled", "LandingViewComponentName", "Name")
VALUES ('NganLuong', '{"IsSandbox":true, "MerchantId": 47249, "MerchantPassword": "e530745693dbde678f9da98a7c821a07", "ReceiverEmail": "nlqthien@gmail.com"}', 'payments-nganluong-config', TRUE, 'NganLuongLanding', 'Ngan Luong Payment');
INSERT INTO "Payments_PaymentProvider" ("Id", "AdditionalSettings", "ConfigureUrl", "IsEnabled", "LandingViewComponentName", "Name")
VALUES ('PaypalExpress', '{ "IsSandbox":true, "ClientId":"", "ClientSecret":"" }', 'payments-paypalExpress-config', TRUE, 'PaypalExpressLanding', 'Paypal Express');
INSERT INTO "Payments_PaymentProvider" ("Id", "AdditionalSettings", "ConfigureUrl", "IsEnabled", "LandingViewComponentName", "Name")
VALUES ('Stripe', '{"PublicKey": "pk_test_6pRNASCoBOKtIshFeQd4XMUh", "PrivateKey" : "sk_test_BQokikJOvBiI2HlWgH4olfQ2"}', 'payments-stripe-config', TRUE, 'StripeLanding', 'Stripe');

INSERT INTO "Shipping_ShippingProvider" ("Id", "AdditionalSettings", "ConfigureUrl", "IsEnabled", "Name", "OnlyCountryIdsString", "OnlyStateOrProvinceIdsString", "ShippingPriceServiceTypeName", "ToAllShippingEnabledCountries", "ToAllShippingEnabledStatesOrProvinces")
VALUES ('FreeShip', '{MinimumOrderAmount : 1}', '', TRUE, 'Free Ship', NULL, NULL, 'SimplCommerce.Module.ShippingFree.Services.FreeShippingServiceProvider,SimplCommerce.Module.ShippingFree', TRUE, TRUE);
INSERT INTO "Shipping_ShippingProvider" ("Id", "AdditionalSettings", "ConfigureUrl", "IsEnabled", "Name", "OnlyCountryIdsString", "OnlyStateOrProvinceIdsString", "ShippingPriceServiceTypeName", "ToAllShippingEnabledCountries", "ToAllShippingEnabledStatesOrProvinces")
VALUES ('TableRate', NULL, 'shipping-table-rate-config', TRUE, 'Table Rate', NULL, NULL, 'SimplCommerce.Module.ShippingTableRate.Services.TableRateShippingServiceProvider,SimplCommerce.Module.ShippingTableRate', TRUE, TRUE);

INSERT INTO "Tax_TaxClass" ("Id", "Name")
VALUES (1, 'Standard VAT');

INSERT INTO "Core_StateOrProvince" ("Id", "Code", "CountryId", "Name", "Type")
VALUES (1, NULL, 'VN', 'Hồ Chí Minh', 'Thành Phố');
INSERT INTO "Core_StateOrProvince" ("Id", "Code", "CountryId", "Name", "Type")
VALUES (2, 'WA', 'US', 'Washington', NULL);

INSERT INTO "Core_UserRole" ("RoleId", "UserId")
VALUES (1, 10);

INSERT INTO "Core_Address" ("Id", "AddressLine1", "AddressLine2", "City", "ContactName", "CountryId", "DistrictId", "Phone", "StateOrProvinceId", "ZipCode")
VALUES (1, '364 Cong Hoa', NULL, NULL, 'Thien Nguyen', 'VN', NULL, NULL, 1, NULL);

INSERT INTO "Core_District" ("Id", "Location", "Name", "StateOrProvinceId", "Type")
VALUES (1, NULL, 'Quận 1', 1, 'Quận');
INSERT INTO "Core_District" ("Id", "Location", "Name", "StateOrProvinceId", "Type")
VALUES (2, NULL, 'Quận 2', 1, 'Quận');

INSERT INTO "Inventory_Warehouse" ("Id", "AddressId", "Name", "VendorId")
VALUES (1, 1, 'Default warehouse', NULL);

CREATE INDEX "IX_ActivityLog_Activity_ActivityTypeId" ON "ActivityLog_Activity" ("ActivityTypeId");

CREATE INDEX "IX_Catalog_Category_ParentId" ON "Catalog_Category" ("ParentId");

CREATE INDEX "IX_Catalog_Category_ThumbnailImageId" ON "Catalog_Category" ("ThumbnailImageId");

CREATE INDEX "IX_Catalog_Product_BrandId" ON "Catalog_Product" ("BrandId");

CREATE INDEX "IX_Catalog_Product_CreatedById" ON "Catalog_Product" ("CreatedById");

CREATE INDEX "IX_Catalog_Product_LatestUpdatedById" ON "Catalog_Product" ("LatestUpdatedById");

CREATE INDEX "IX_Catalog_Product_TaxClassId" ON "Catalog_Product" ("TaxClassId");

CREATE INDEX "IX_Catalog_Product_ThumbnailImageId" ON "Catalog_Product" ("ThumbnailImageId");

CREATE INDEX "IX_Catalog_ProductAttribute_GroupId" ON "Catalog_ProductAttribute" ("GroupId");

CREATE INDEX "IX_Catalog_ProductAttributeValue_AttributeId" ON "Catalog_ProductAttributeValue" ("AttributeId");

CREATE INDEX "IX_Catalog_ProductAttributeValue_ProductId" ON "Catalog_ProductAttributeValue" ("ProductId");

CREATE INDEX "IX_Catalog_ProductCategory_CategoryId" ON "Catalog_ProductCategory" ("CategoryId");

CREATE INDEX "IX_Catalog_ProductCategory_ProductId" ON "Catalog_ProductCategory" ("ProductId");

CREATE INDEX "IX_Catalog_ProductLink_LinkedProductId" ON "Catalog_ProductLink" ("LinkedProductId");

CREATE INDEX "IX_Catalog_ProductLink_ProductId" ON "Catalog_ProductLink" ("ProductId");

CREATE INDEX "IX_Catalog_ProductMedia_MediaId" ON "Catalog_ProductMedia" ("MediaId");

CREATE INDEX "IX_Catalog_ProductMedia_ProductId" ON "Catalog_ProductMedia" ("ProductId");

CREATE INDEX "IX_Catalog_ProductOptionCombination_OptionId" ON "Catalog_ProductOptionCombination" ("OptionId");

CREATE INDEX "IX_Catalog_ProductOptionCombination_ProductId" ON "Catalog_ProductOptionCombination" ("ProductId");

CREATE INDEX "IX_Catalog_ProductOptionValue_OptionId" ON "Catalog_ProductOptionValue" ("OptionId");

CREATE INDEX "IX_Catalog_ProductOptionValue_ProductId" ON "Catalog_ProductOptionValue" ("ProductId");

CREATE INDEX "IX_Catalog_ProductPriceHistory_CreatedById" ON "Catalog_ProductPriceHistory" ("CreatedById");

CREATE INDEX "IX_Catalog_ProductPriceHistory_ProductId" ON "Catalog_ProductPriceHistory" ("ProductId");

CREATE INDEX "IX_Catalog_ProductTemplateProductAttribute_ProductAttributeId" ON "Catalog_ProductTemplateProductAttribute" ("ProductAttributeId");

CREATE INDEX "IX_Checkouts_Checkout_CreatedById" ON "Checkouts_Checkout" ("CreatedById");

CREATE INDEX "IX_Checkouts_Checkout_CustomerId" ON "Checkouts_Checkout" ("CustomerId");

CREATE INDEX "IX_Checkouts_CheckoutItem_CheckoutId" ON "Checkouts_CheckoutItem" ("CheckoutId");

CREATE INDEX "IX_Checkouts_CheckoutItem_ProductId" ON "Checkouts_CheckoutItem" ("ProductId");

CREATE INDEX "IX_Cms_MenuItem_EntityId" ON "Cms_MenuItem" ("EntityId");

CREATE INDEX "IX_Cms_MenuItem_MenuId" ON "Cms_MenuItem" ("MenuId");

CREATE INDEX "IX_Cms_MenuItem_ParentId" ON "Cms_MenuItem" ("ParentId");

CREATE INDEX "IX_Cms_Page_CreatedById" ON "Cms_Page" ("CreatedById");

CREATE INDEX "IX_Cms_Page_LatestUpdatedById" ON "Cms_Page" ("LatestUpdatedById");

CREATE INDEX "IX_Comments_Comment_ParentId" ON "Comments_Comment" ("ParentId");

CREATE INDEX "IX_Comments_Comment_UserId" ON "Comments_Comment" ("UserId");

CREATE INDEX "IX_Contacts_Contact_ContactAreaId" ON "Contacts_Contact" ("ContactAreaId");

CREATE INDEX "IX_Core_Address_CountryId" ON "Core_Address" ("CountryId");

CREATE INDEX "IX_Core_Address_DistrictId" ON "Core_Address" ("DistrictId");

CREATE INDEX "IX_Core_Address_StateOrProvinceId" ON "Core_Address" ("StateOrProvinceId");

CREATE UNIQUE INDEX "IX_Core_CustomerGroup_Name" ON "Core_CustomerGroup" ("Name");

CREATE INDEX "IX_Core_CustomerGroupUser_CustomerGroupId" ON "Core_CustomerGroupUser" ("CustomerGroupId");

CREATE INDEX "IX_Core_District_StateOrProvinceId" ON "Core_District" ("StateOrProvinceId");

CREATE INDEX "IX_Core_Entity_EntityTypeId" ON "Core_Entity" ("EntityTypeId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "Core_Role" ("NormalizedName");

CREATE INDEX "IX_Core_RoleClaim_RoleId" ON "Core_RoleClaim" ("RoleId");

CREATE INDEX "IX_Core_StateOrProvince_CountryId" ON "Core_StateOrProvince" ("CountryId");

CREATE INDEX "EmailIndex" ON "Core_User" ("NormalizedEmail");

CREATE INDEX "IX_Core_User_DefaultBillingAddressId" ON "Core_User" ("DefaultBillingAddressId");

CREATE INDEX "IX_Core_User_DefaultShippingAddressId" ON "Core_User" ("DefaultShippingAddressId");

CREATE INDEX "IX_Core_User_VendorId" ON "Core_User" ("VendorId");

CREATE UNIQUE INDEX "UserNameIndex" ON "Core_User" ("NormalizedUserName");

CREATE INDEX "IX_Core_UserAddress_AddressId" ON "Core_UserAddress" ("AddressId");

CREATE INDEX "IX_Core_UserAddress_UserId" ON "Core_UserAddress" ("UserId");

CREATE INDEX "IX_Core_UserClaim_UserId" ON "Core_UserClaim" ("UserId");

CREATE INDEX "IX_Core_UserLogin_UserId" ON "Core_UserLogin" ("UserId");

CREATE INDEX "IX_Core_UserRole_RoleId" ON "Core_UserRole" ("RoleId");

CREATE INDEX "IX_Core_WidgetInstance_WidgetId" ON "Core_WidgetInstance" ("WidgetId");

CREATE INDEX "IX_Core_WidgetInstance_WidgetZoneId" ON "Core_WidgetInstance" ("WidgetZoneId");

CREATE INDEX "IX_Inventory_Stock_ProductId" ON "Inventory_Stock" ("ProductId");

CREATE INDEX "IX_Inventory_Stock_WarehouseId" ON "Inventory_Stock" ("WarehouseId");

CREATE INDEX "IX_Inventory_StockHistory_CreatedById" ON "Inventory_StockHistory" ("CreatedById");

CREATE INDEX "IX_Inventory_StockHistory_ProductId" ON "Inventory_StockHistory" ("ProductId");

CREATE INDEX "IX_Inventory_StockHistory_WarehouseId" ON "Inventory_StockHistory" ("WarehouseId");

CREATE INDEX "IX_Inventory_Warehouse_AddressId" ON "Inventory_Warehouse" ("AddressId");

CREATE INDEX "IX_Inventory_Warehouse_VendorId" ON "Inventory_Warehouse" ("VendorId");

CREATE INDEX "IX_Localization_LocalizedContentProperty_CultureId" ON "Localization_LocalizedContentProperty" ("CultureId");

CREATE INDEX "IX_Localization_Resource_CultureId" ON "Localization_Resource" ("CultureId");

CREATE INDEX "IX_News_NewsItem_CreatedById" ON "News_NewsItem" ("CreatedById");

CREATE INDEX "IX_News_NewsItem_LatestUpdatedById" ON "News_NewsItem" ("LatestUpdatedById");

CREATE INDEX "IX_News_NewsItem_ThumbnailImageId" ON "News_NewsItem" ("ThumbnailImageId");

CREATE INDEX "IX_News_NewsItemCategory_NewsItemId" ON "News_NewsItemCategory" ("NewsItemId");

CREATE INDEX "IX_Orders_Order_BillingAddressId" ON "Orders_Order" ("BillingAddressId");

CREATE INDEX "IX_Orders_Order_CreatedById" ON "Orders_Order" ("CreatedById");

CREATE INDEX "IX_Orders_Order_CustomerId" ON "Orders_Order" ("CustomerId");

CREATE INDEX "IX_Orders_Order_LatestUpdatedById" ON "Orders_Order" ("LatestUpdatedById");

CREATE INDEX "IX_Orders_Order_ParentId" ON "Orders_Order" ("ParentId");

CREATE INDEX "IX_Orders_Order_ShippingAddressId" ON "Orders_Order" ("ShippingAddressId");

CREATE INDEX "IX_Orders_OrderAddress_CountryId" ON "Orders_OrderAddress" ("CountryId");

CREATE INDEX "IX_Orders_OrderAddress_DistrictId" ON "Orders_OrderAddress" ("DistrictId");

CREATE INDEX "IX_Orders_OrderAddress_StateOrProvinceId" ON "Orders_OrderAddress" ("StateOrProvinceId");

CREATE INDEX "IX_Orders_OrderHistory_CreatedById" ON "Orders_OrderHistory" ("CreatedById");

CREATE INDEX "IX_Orders_OrderHistory_OrderId" ON "Orders_OrderHistory" ("OrderId");

CREATE INDEX "IX_Orders_OrderItem_OrderId" ON "Orders_OrderItem" ("OrderId");

CREATE INDEX "IX_Orders_OrderItem_ProductId" ON "Orders_OrderItem" ("ProductId");

CREATE INDEX "IX_Payments_Payment_OrderId" ON "Payments_Payment" ("OrderId");

CREATE INDEX "IX_Pricing_CartRuleCategory_CategoryId" ON "Pricing_CartRuleCategory" ("CategoryId");

CREATE INDEX "IX_Pricing_CartRuleCustomerGroup_CustomerGroupId" ON "Pricing_CartRuleCustomerGroup" ("CustomerGroupId");

CREATE INDEX "IX_Pricing_CartRuleProduct_ProductId" ON "Pricing_CartRuleProduct" ("ProductId");

CREATE INDEX "IX_Pricing_CartRuleUsage_CartRuleId" ON "Pricing_CartRuleUsage" ("CartRuleId");

CREATE INDEX "IX_Pricing_CartRuleUsage_CouponId" ON "Pricing_CartRuleUsage" ("CouponId");

CREATE INDEX "IX_Pricing_CartRuleUsage_UserId" ON "Pricing_CartRuleUsage" ("UserId");

CREATE INDEX "IX_Pricing_CatalogRuleCustomerGroup_CustomerGroupId" ON "Pricing_CatalogRuleCustomerGroup" ("CustomerGroupId");

CREATE INDEX "IX_Pricing_Coupon_CartRuleId" ON "Pricing_Coupon" ("CartRuleId");

CREATE INDEX "IX_ProductComparison_ComparingProduct_ProductId" ON "ProductComparison_ComparingProduct" ("ProductId");

CREATE INDEX "IX_ProductComparison_ComparingProduct_UserId" ON "ProductComparison_ComparingProduct" ("UserId");

CREATE INDEX "IX_Reviews_Reply_ReviewId" ON "Reviews_Reply" ("ReviewId");

CREATE INDEX "IX_Reviews_Reply_UserId" ON "Reviews_Reply" ("UserId");

CREATE INDEX "IX_Reviews_Review_UserId" ON "Reviews_Review" ("UserId");

CREATE INDEX "IX_Shipments_Shipment_CreatedById" ON "Shipments_Shipment" ("CreatedById");

CREATE INDEX "IX_Shipments_Shipment_OrderId" ON "Shipments_Shipment" ("OrderId");

CREATE INDEX "IX_Shipments_Shipment_WarehouseId" ON "Shipments_Shipment" ("WarehouseId");

CREATE INDEX "IX_Shipments_ShipmentItem_ProductId" ON "Shipments_ShipmentItem" ("ProductId");

CREATE INDEX "IX_Shipments_ShipmentItem_ShipmentId" ON "Shipments_ShipmentItem" ("ShipmentId");

CREATE INDEX "IX_ShippingTableRate_PriceAndDestination_CountryId" ON "ShippingTableRate_PriceAndDestination" ("CountryId");

CREATE INDEX "IX_ShippingTableRate_PriceAndDestination_DistrictId" ON "ShippingTableRate_PriceAndDestination" ("DistrictId");

CREATE INDEX "IX_ShippingTableRate_PriceAndDestination_StateOrProvinceId" ON "ShippingTableRate_PriceAndDestination" ("StateOrProvinceId");

CREATE INDEX "IX_ShoppingCart_CartItem_CustomerId" ON "ShoppingCart_CartItem" ("CustomerId");

CREATE INDEX "IX_ShoppingCart_CartItem_ProductId" ON "ShoppingCart_CartItem" ("ProductId");

CREATE INDEX "IX_Tax_TaxRate_CountryId" ON "Tax_TaxRate" ("CountryId");

CREATE INDEX "IX_Tax_TaxRate_StateOrProvinceId" ON "Tax_TaxRate" ("StateOrProvinceId");

CREATE INDEX "IX_Tax_TaxRate_TaxClassId" ON "Tax_TaxRate" ("TaxClassId");

CREATE INDEX "IX_WishList_WishList_UserId" ON "WishList_WishList" ("UserId");

CREATE INDEX "IX_WishList_WishListItem_ProductId" ON "WishList_WishListItem" ("ProductId");

CREATE INDEX "IX_WishList_WishListItem_WishListId" ON "WishList_WishListItem" ("WishListId");

ALTER TABLE "Catalog_Product" ADD CONSTRAINT "FK_Catalog_Product_Core_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Catalog_Product" ADD CONSTRAINT "FK_Catalog_Product_Core_User_LatestUpdatedById" FOREIGN KEY ("LatestUpdatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Catalog_ProductPriceHistory" ADD CONSTRAINT "FK_Catalog_ProductPriceHistory_Core_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Checkouts_Checkout" ADD CONSTRAINT "FK_Checkouts_Checkout_Core_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Checkouts_Checkout" ADD CONSTRAINT "FK_Checkouts_Checkout_Core_User_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Cms_Page" ADD CONSTRAINT "FK_Cms_Page_Core_User_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Cms_Page" ADD CONSTRAINT "FK_Cms_Page_Core_User_LatestUpdatedById" FOREIGN KEY ("LatestUpdatedById") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Comments_Comment" ADD CONSTRAINT "FK_Comments_Comment_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Core_CustomerGroupUser" ADD CONSTRAINT "FK_Core_CustomerGroupUser_Core_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Core_User" ("Id") ON DELETE CASCADE;

ALTER TABLE "Core_User" ADD CONSTRAINT "FK_Core_User_Core_UserAddress_DefaultBillingAddressId" FOREIGN KEY ("DefaultBillingAddressId") REFERENCES "Core_UserAddress" ("Id") ON DELETE RESTRICT;

ALTER TABLE "Core_User" ADD CONSTRAINT "FK_Core_User_Core_UserAddress_DefaultShippingAddressId" FOREIGN KEY ("DefaultShippingAddressId") REFERENCES "Core_UserAddress" ("Id") ON DELETE RESTRICT;

SELECT setval(
    pg_get_serial_sequence('"ActivityLog_ActivityType"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "ActivityLog_ActivityType") + 1,
        nextval(pg_get_serial_sequence('"ActivityLog_ActivityType"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Catalog_ProductOption"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Catalog_ProductOption") + 1,
        nextval(pg_get_serial_sequence('"Catalog_ProductOption"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Cms_Menu"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Cms_Menu") + 1,
        nextval(pg_get_serial_sequence('"Cms_Menu"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Core_Role"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Core_Role") + 1,
        nextval(pg_get_serial_sequence('"Core_Role"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Core_User"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Core_User") + 1,
        nextval(pg_get_serial_sequence('"Core_User"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Core_WidgetZone"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Core_WidgetZone") + 1,
        nextval(pg_get_serial_sequence('"Core_WidgetZone"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Tax_TaxClass"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Tax_TaxClass") + 1,
        nextval(pg_get_serial_sequence('"Tax_TaxClass"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Core_StateOrProvince"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Core_StateOrProvince") + 1,
        nextval(pg_get_serial_sequence('"Core_StateOrProvince"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Core_Address"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Core_Address") + 1,
        nextval(pg_get_serial_sequence('"Core_Address"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Core_District"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Core_District") + 1,
        nextval(pg_get_serial_sequence('"Core_District"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Inventory_Warehouse"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Inventory_Warehouse") + 1,
        nextval(pg_get_serial_sequence('"Inventory_Warehouse"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251014191230_initialSchema', '9.0.1');

COMMIT;

