insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('SU', 'AEROFLOT', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('HZ',	'SATAIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('GH', 'GLOBUS', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('5N', 'ARCHANGELSK AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('Y7', 'TAIMYR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('N4', 'NORDWIND', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('DP', 'POBEDA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('WZ', 'RED WINGS', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('FV', 'RUSSIA AIRLINES', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('S7', 'SIBERIAN AIRLINES', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('U6', 'SVERDLOVSK AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('UT', 'UTAIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('R3', 'AIR YAKUTIA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('YC', 'YAMAL', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('ABAKAN AIR',	'ABAKAN AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('AEROBRA', 'AEROBRA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('AEROLIMOUSINE', 'AEROLIMOUSINE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('ZF', 'KATEKAVIA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('BALTIC AIRLINES', 'BALTIC AIRLINES', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('4G', 'GAZPROM', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('ZG', 'GROZNYY AVIA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('H5','RUSSIAN SKY', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('IO', 'IRAERO', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('I8', 'IZHAVIA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('IK', 'IKAR AIRLINES', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('ABAKAN-AVIA', 'ABAKAN-AVIA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('7R', 'RUSLINE AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('6W', 'SARATOV AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('TK', 'ANADOLUJET', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('KK', 'ATLASGLOBAL', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('YB', 'BORAJET', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('XC', 'CORENDON AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('FH', 'FREEBIRD', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('4I', 'IZ AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('8Q', 'ONUR AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('PC', 'PEGASUS AIRLINES', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('XQ', 'SUNEXPRESS', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('TI', 'TAILWIND', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('TK', 'TURKISH AIRLINES', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('KC', 'ASTANALINE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('Z9', 'BEKAIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('DV', 'VLASTA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('ONX', 'ONIXAIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('UKR', 'AIR UKRAINE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('DAT', 'TRANS KIEV', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('UDC', 'DONBASS AERO', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('CRF', 'KRYM AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('LHS', 'ENTERPRISE LUHANSK', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('UKW', 'UKRAINE WEST', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('OTL', 'SOUTHLINE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('VRE', 'UKRAINE VOLARE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('WAU', 'WIZZAIR UKRAINE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('PS', 'UKRAINE INTERNATIONAL', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('3N', 'URGA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('UH', 'ATLASGLOBAL', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('QU', 'UT-UKRAINE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('D4', 'DART AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('Z6', 'DNIEPROAVIA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('M9', 'MOTOR SICH', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('KT', 'KHARKIV AIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('UF', 'UKRAINE MEDITERRANEE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('YE', 'YANAIR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('DW', 'CHARTER UKRAINE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('AEROSTAR', 'AEROSTAR', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('BRAVO AIRWAYS', 'BRAVO AIRWAYS', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('BQ', 'BUKOVYNA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('BUSINESS AVIATION', 'BUSINESS AVIATION', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('SKY CHALLENGER', 'SKY CHALLENGER', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('CONSTANTA', 'CONSTANTA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('ENTERPRISE UKRAINE', 'ENTERPRISE UKRAINE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('7W', 'WIND ROSE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('2N',	'YUZMASH', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('AEROVIZ', 'AEROVIZ', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('ANTONOV BUREAU','ANTONOV BUREAU', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('UKRAINE ALLIANCE', 'UKRAINE ALLIANCE', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('AIR-ARP', 'AIR-ARP', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('KHORIV-AVIA', 'KHORIV-AVIA', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('KO',	'AIRCOMPANY KHORS', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('6V', 'AVIAMARS', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('RIVNE UNIVERSAL', 'RIVNE UNIVERSAL', 0, 1)
insert into Catalog_Brand (Description, Name, IsDeleted, IsPublished) values ('5G', 'ANDA AIR', 0, 1)