INSERT INTO [Core_StateOrProvince] ([CountryId], [Code], [Name]) VALUES
('US', 'AL', 'Alabama'),
('US', 'AK', 'Alaska'),
('US', 'AS', 'American Samoa'),
('US', 'AZ', 'Arizona'),
('US', 'AR', 'Arkansas'),
('US', 'AE', 'Armed Forces Africa'),
('US', 'AA', 'Armed Forces Americas'),
('US', 'AE', 'Armed Forces Canada'),
('US', 'AE', 'Armed Forces Europe'),
('US', 'AE', 'Armed Forces Middle East'),
('US', 'AP', 'Armed Forces Pacific'),
('US', 'CA', 'California'),
('US', 'CO', 'Colorado'),
('US', 'CT', 'Connecticut'),
('US', 'DE', 'Delaware'),
('US', 'DC', 'District of Columbia'),
('US', 'FM', 'Federated States Of Micronesia'),
('US', 'FL', 'Florida'),
('US', 'GA', 'Georgia'),
('US', 'GU', 'Guam'),
('US', 'HI', 'Hawaii'),
('US', 'ID', 'Idaho'),
('US', 'IL', 'Illinois'),
('US', 'IN', 'Indiana'),
('US', 'IA', 'Iowa'),
('US', 'KS', 'Kansas'),
('US', 'KY', 'Kentucky'),
('US', 'LA', 'Louisiana'),
('US', 'ME', 'Maine'),
('US', 'MH', 'Marshall Islands'),
('US', 'MD', 'Maryland'),
('US', 'MA', 'Massachusetts'),
('US', 'MI', 'Michigan'),
('US', 'MN', 'Minnesota'),
('US', 'MS', 'Mississippi'),
('US', 'MO', 'Missouri'),
('US', 'MT', 'Montana'),
('US', 'NE', 'Nebraska'),
('US', 'NV', 'Nevada'),
('US', 'NH', 'New Hampshire'),
('US', 'NJ', 'New Jersey'),
('US', 'NM', 'New Mexico'),
('US', 'NY', 'New York'),
('US', 'NC', 'North Carolina'),
('US', 'ND', 'North Dakota'),
('US', 'MP', 'Northern Mariana Islands'),
('US', 'OH', 'Ohio'),
('US', 'OK', 'Oklahoma'),
('US', 'OR', 'Oregon'),
('US', 'PW', 'Palau'),
('US', 'PA', 'Pennsylvania'),
('US', 'PR', 'Puerto Rico'),
('US', 'RI', 'Rhode Island'),
('US', 'SC', 'South Carolina'),
('US', 'SD', 'South Dakota'),
('US', 'TN', 'Tennessee'),
('US', 'TX', 'Texas'),
('US', 'UT', 'Utah'),
('US', 'VT', 'Vermont'),
('US', 'VI', 'Virgin Islands'),
('US', 'VA', 'Virginia'),
--('US', 'WA', 'Washington'),
('US', 'WV', 'West Virginia'),
('US', 'WI', 'Wisconsin'),
('US', 'WY', 'Wyoming')
GO
