INSERT [dbo].[Localization_Culture] ([Id], [Name]) VALUES ('de-DE', N'German')
GO

INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Register', N'S''Registrieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Hello {0}!', N'Hallo {0}!')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Log in', N'Anmelden')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Log off', N'Abmelden')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'The Email field is required.', N'Email ist ein Pflichtfeld.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Email', N'Email')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'User List', N'Benutzerliste')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Remember me?', N'An mich erinnern?')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Password', N'Passwort')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Use a local account to log in.', N'Anmelden mit meinem lokalen Benutzerkonto.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Register as a new user?', N'Ein Benutzerkonto anlegen?')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Forgot your password?', N'Passwort vergessen?')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Use another service to log in.', N'Mit einem anderen Benutzerkonto anmelden.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Full name', N'Benutzername')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Confirm password', N'Passwort wiederholen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create a new account.', N'Ein neues Benutzerkonto anlegen.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'All', N'Alle')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Home', N'Startseite')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Add to cart', N'In den Warenkorb')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product detail', N'Produktdetails')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product specification', N'Produkteigenschaften')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Rate this product', N'Produkt bewerten')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Review comment', N'Bewertungstext')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Review title', N'Bewertungsüberschrift')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Posted by', N'Gesendet von')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Submit review', N'Bewertung absenden')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'You have', N'Sie haben')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'products in your cart', N'Produkte in Ihrem Warenkorb')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Continue shopping', N'Weiter einkaufen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'View cart', N'Warenkorb ansehen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'The product has been added to your cart', N'Das Produkt wurde in den Warenkorb gelegt')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Cart subtotal', N'Zwischensumme Warenkorb')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Shopping Cart', N'Warenkorb')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product', N'Produkt')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Price', N'Preis')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Quantity', N'Anzahl')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'There are no items in this cart.', N'Der Warenkorb ist leer.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Go to shopping', N'Kaufen Sie ein')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Order summary', N'Bestellübersicht')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Subtotal', N'Zwischensumme')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Process to Checkout', N'Zur Kasse gehen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Shipping address', N'Versandadresse')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Add another address', N'Eine weitere Adresse hinzufügen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Contact name', N'Name des Kontakts')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Address', N'Adresse')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'State or Province', N'Bundesland')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'District', N'Bezirk')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Phone', N'Telefon')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Order', N'Bestellung')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'products', N'Produkte')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'reviews', N'Bewertungen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Add Review', N'Bewertung hinzufügen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Customer reviews', N'Kundenbewertungen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Your review will be shown within the next 24h.', N'Ihre Bewertung erscheint binnen 24 Stunden.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Thank you {0} for your review', N'Danke {0} für Ihre Bestellung')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Rating average', N'Durchschnittliche Bewertung')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'stars', N'Sterne')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Filter by', N'Filtern nach')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Category', N'Kategorie')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Brand', N'Marke')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Sort by:', N'Sortieren nach:')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'results', N'Ergebnisse')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'View options', N'Anzeigeoptionen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Associate your {0} account.', N'Benutzerkonto {0} verknüpfen.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Users', N'Benutzer')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Vendors', N'Verkäufer')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Reviews', N'Bewertungen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Products', N'Produkte')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Categories', N'Kategorien')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Brands', N'Marken')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product Options', N'Produktoptionen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product Attribute', N'Produkteigenschaften')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product Attribute Groups', N'Produkteigenschaftsgruppen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product Templates', N'Produktvorlagen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Sales', N'Verkäufe')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Orders', N'Bestellungen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Content Management', N'Inhalte verwalten')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Pages', N'Seiten')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Widgets', N'Widgets')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'System', N'System')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Configuration', N'Konfiguration')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Translations', N'Übersetzungen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Dashboard', N'Dashboard')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Incomplete orders', N'Unvollständige Bestellungen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Pending reviews', N'Ausstehende Bewertungen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Most searched keywords', N'Am häufigsten gesuchte Wörter')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Most viewed products', N'Am häufigsten besuchte Produkte')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'OrderId', N'Bestellnummer')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Order Status', N'Bestellstatus')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Customer', N'Kunde')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Created On', N'Erstellt am')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'SubTotal', N'Zwischensumme')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Actions', N'Aktionen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Site', N'Site')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Catalog', N'Katalog')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Title', N'Titel')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Comment', N'Kommentar')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Status', N'Status')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Rating', N'Bewertung')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Keyword', N'Schlüsselwort')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Count', N'Anzahl')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create User', N'Benutzer anlegen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'FullName', N'Benutzername')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Roles', N'Rollen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit User', N'Benutzer editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Manager of Vendor', N'Manager des Verkäufers')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Save', N'Speichern')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Cancel', N'Abbrechen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Phone Number', N'Telefonnummer')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Vendor', N'Verkäufer anlegen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Is Active', N'Aktiv')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Vendor', N'Verkäufer editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Managers', N'Manager')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Description', N'Beschreibung')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Pending', N'Ausstehend')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Approved', N'Bestätigt')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Not Approved', N'Unbestätigt')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Approve', N'Bestätigen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Product', N'Produkt anlegen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Has Options', N'Hat Optionen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Is Visible Individually', N'Ist einzeln sichtbar')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Is Featured', N'Ist ausgezeichnet')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Is Allowed To Order', N'Bestellbar')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Is Called For Pricing', N'Preis auf Anfrage')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Stock Quantity', N'Lagerbestand')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Is Published', N'Ist publiziert')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Yes', N'Ja')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'No', N'Nein')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Product', N'Produkt editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product Name', N'Produktname')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Short Description', N'Kurzbeschreibung')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Specification', N'Spezifikation')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Old Price', N'Alter Preis')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Special Price', N'Sonderpreis')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Special Price Start', N'Sonderpreis ab')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Special Price End', N'Sonderpreis bis')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Thumbnail', N'Thumbnail')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product Images', N'Produktbilder')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product Documents', N'Produkt-Dokumente')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Out Of Stock', N'Nicht auf Lager')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Available Options', N'Verfügbare Optionen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Add Option', N'Option hinzufügen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Option Values', N'Optionswerte')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Delete Option', N'Option löschen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Generate Combinations', N'Kombination erstellen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product Variations', N'Produktvariationen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Option Combinations', N'Optionskombinationen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Images', N'Bilder')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Apply', N'Anwenden')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Available Attributes', N'Verfügbare Eigenschaften')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Add Attribute', N'Eigenschaft hinzufügen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product Attributes', N'Produkteigenschaften')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Attribute Name', N'Eigenschaftsname')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Value', N'Wert')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'General Information', N'Allgemeine Informationen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Category Mapping', N'Kategoriezuordnung')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Related Products', N'Verwandte Produkte')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Manage Related Products', N'Verwandte Produkte verwalten')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Category', N'Kategorie erstellen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Category', N'Kategorie editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Brand', N'Marke erstellen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Brand', N'Marke editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Name', N'Name')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Parent Category', N'Übergeordnete Kategorie')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Group', N'Gruppe')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Product Attribute', N'Produkteigenschaft erstellen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Product Attribute', N'Produkteigenschaft editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Product Attribute Group', N'Produkteigenschaftsgruppe erstellen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Product Attribute Group', N'Produkteigenschaftsgruppe editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Product Option', N'Produktoption erstellen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Product Option', N'Produktoption editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Product Display Widget', N'Widget für Produktanzeige erstellen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Product Display Widget', N'Widget für Produktanzeige editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Widget Name', N'Widget-Name')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Widget Zone', N'Widget Zone')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Publish Start', N'Veröffentlichung ab')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Publish End', N'Veröffentlichung bis')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Number of Products', N'Anzahl Produkte')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Order By', N'Sortieren nach')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Product Template', N'Produktvorlage erstellen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Product Template', N'Produktvorlage editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Added Attributes', N'Hinzugefügte Eigenschaften')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Back', N'Zurück')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Order Detail', N'Bestelldetails')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Order Information', N'Bestellinformationen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Change', N'Ändern')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Product Information', N'Produktinformation')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Shipping Information', N'Lieferinformationen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Application Settings', N'Anwendungseinstellungen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Page', N'Seite erstellen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Page', N'Seite bearbeiten')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Body', N'Inhalt')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Account Dashboard', N'Benutzerkonten-Dashboard')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Account Information', N'Benutzerkonteninformationen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit', N'Editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Security', N'Sicherheit')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create', N'Erstellt')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'External Logins', N'Externe Anmeldungen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Manage', N'Verwalten')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Default shipping address', N'Standard-Lieferadresse')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Manage address', N'Adressen verwalten')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'You don''t have any default address', N'Sie haben noch keine Standardadresse')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Order History', N'Bestellübersicht')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Address Book', N'Adressbuch')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Add Address', N'Adresse hinzufügen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Delete', N'Löschen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Set as default shipping address', N'Als Standard-Lieferadresse festlegen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Edit Address', N'Adresse editieren')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Create Address', N'Adresse erstellen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Your account', N'Ihr Benutzerkonto')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Date', N'Datum')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Add to Compare', N'Zum vergleichen hinzufügen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Not available', N'Nicht verfügbar')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'You save', N'Sie sparen')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Submit', N'Absenden')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'All Categories', N'Alle Kategorien')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('de-DE', N'Search here...', N'Hier suchen...')
GO
