INSERT [dbo].[Localization_Culture] ([Id], [Name]) VALUES ('fa-IR', N'فارسی')
GO

INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Register', N'ثبت‌نام')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Hello {0}!', N'سلام {0}!')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Log in', N'ورود')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Log off', N'خروج')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'The Email field is required.', N'وارد کردن ایمیل ضروری است.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Email', N'ایمیل')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'User List', N'لیست کاربران')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Remember me?', N'مرا به خاطر داشته باش?')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Password', N'کلمه عبور')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Use a local account to log in.', N'اطلاعات کاربری خود را وارد نمایید.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Register as a new user?', N'ثبت نام کاربر جدید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Forgot your password?', N'کلمه عبور خود را فراموش کردید؟')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Use another service to log in.', N'با استفاده از سرویس‌های دیگر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Full name', N'نام کامل')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Confirm password', N'تکرار کلمه عبور')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Create a new account.', N'ساخت اکانت جدید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'All', N'همه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Home', N'خانه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Add to cart', N'اضافه به سبد')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Product detail', N'مشخصات محصول')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Product specification', N'ویژگی‌های محصول')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Rate this product', N'به این محصول امتیاز بدهید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Review comment', N'بررسی نظر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Review title', N'بررسی عنوان')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Posted by', N'پست شده توسط')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Submit review', N'اظاف کردن نظر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'You have', N'دارید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'products in your cart', N'محصولات سبد شما')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Continue shopping', N'ادامه خرید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'View cart', N'مشاهده سبد خرید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'The product has been added to your cart', N'محصول به سبد شما اضافه شد')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Cart subtotal', N'مجموع')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Shopping Cart', N'سبد خرید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Product', N'محصول')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Price', N'قیمت')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Quantity', N'مقدار')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'There are no items in this cart.', N'سبد خرید خالی است.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Go to shopping', N'خرید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Order summary', N'خلاصه سفارش')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Subtotal', N'مجموع')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Process to Checkout', N'پایان خرید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Shipping address', N'آدرس تحویل')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Add another address', N'اضافه کردن آدرس جدید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Contact name', N'نام')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Address', N'آدرس')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'State or Province', N'استان')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'District', N'ناحیه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Phone', N'تلفن')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Order', N'سفارش')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'products', N'محصولات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'reviews', N'نظرات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Add Review', N'اضافه کردن نظر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Customer reviews', N'نظرات کاربران')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Your review will be showed within the next 24h.', N'نظر شما بعد از بررسی نمایش داده خواهد شد.')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Thank you {0} for your review', N'{0} ممنون از نظر ')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Rating average', N'میانگین امتیاز‌ها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'stars', N'امتیازها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Filter by', N'فیلتر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Category', N'دسته')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Brand', N'برند')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Sort by:', N'مرتب سازی:')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'results', N'نتایج')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Users', N'کاربران')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Vendors', N'فروشنده‌ها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Reviews', N'نظرات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Products', N'محصولات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Categories', N'دسته‌ها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Brands', N'برندها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Product Attribute Groups', N'ویژگی‌های محصولات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Product Templates', N'قالب‌های محصولات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Sales', N'فروش')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Orders', N'سفارش‌ها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Content Management', N'مدیریت محتوا')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Pages', N'صفحات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Widgets', N'Widgets')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'System', N'سیستم')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Configuration', N'تنظیمات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Translations', N'ترجمه‌ها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Dashboard', N'دشبورد')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Incomplete orders', N'سفارشات ناتمام')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Pending reviews', N'نظرات منتظر تایید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Most searched keywords', N'بیشترین جستجوها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Most viewed products', N'بیشنترین مشاهده')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'OrderId', N'شناسه سفارش')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Order Status', N'وضعیت سفارش')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Customer', N'مشتری')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Created On', N'زمان ایجاد')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'SubTotal', N'مجموع')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Actions', N'عملیات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Site', N'سایت')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Catalog', N'دسته')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Title', N'عنوان')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Comment', N'نظر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Status', N'وضعیت')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Rating', N'امتیاز')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Keyword', N'کی‌ورد')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Count', N'تعداد')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Create User', N'ایجاد کاربر جدید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'FullName', N'نام کامل')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Roles', N'نقش‌ها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Edit User', N'ویرایش کاربر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Manager of Vendor', N'مدیر فروشنده')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Save', N'ذخیره')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Cancel', N'انصراف')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Phone Number', N'شماره تماس')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Create Vendor', N'ایجاد فروشنده')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Is Active', N'فعال')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Edit Vendor', N'ویرایش فروشنده')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Managers', N'Les مدیران')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Description', N'توضیحات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Pending', N'در انتظار')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Approved', N'تایید شده')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Not Approved', N'تایید نشده')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Approve', N'تایید')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Create Product', N'ایجاد محصول')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Is Featured', N'توصیه شده')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Is Published', N'پابلیش شده')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Yes', N'بله')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'No', N'خیر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Edit Product', N'ویرایش محصول')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Product Name', N'نام محصول')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Short Description', N'توضیح کوتاه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Specification', N'ویژگی‌ها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Old Price', N'قیمت قدیم')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Special Price', N'قیمت ویژه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Thumbnail', N'تصویر کوچک')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Product Images', N'تصویر محصول')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Images', N'تصاویر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Apply', N'اعمال')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Attribute Name', N'نام مشخصه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Value', N'مقدار')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'General Information', N'اطلاعات کلی')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Related Products', N'محصولات مشابه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Manage Related Products', N'مدیریت محصولات مشابه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Create Category', N'ایجاد دسته')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Edit Category', N'ویرایش دسته')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Create Brand', N'ایجاد برند')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Edit Brand', N'ویرایش برند')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Name', N'نام')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Parent Category', N'دسته پدر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Group', N'گروه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Publish Start', N'شروع پابلیش')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Publish End', N'پایان پابلش')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Number of Products', N'تعداد محصولات')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Order By', N'ترتیب')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Back', N'بازگشت')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Change', N'تغییر')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Product Information', N'مشخصات محصول')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Application Settings', N'تنظیمات برنامه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Create Page', N'ایجاد صفحه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Edit Page', N'ویرایش صفحه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Body', N'بدنه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Edit', N'ویرایش')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Security', N'Sécurité')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Create', N'ایجاد')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Manage', N'مدیریت')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Order History', N'تاریخچه سفارش‌ها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Address Book', N'آدرس‌ها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Add Address', N'اضافه کردن آدرس')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Delete', N'حذف')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Set as default shipping address', N'آدرس پیش فرض')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Edit Address', N'ویرایش آدرس')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Create Address', N'اضافه کردن آدرس')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Your account', N'اکانت شما')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Date', N'تاریخ')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Add to Compare', N'مقایسه')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Not available', N'در دسترس نیست')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'You save', N'تخفیف شما')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Submit', N'ثبت')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'All Categories', N'همه دسته‌ها')
INSERT [dbo].[Localization_Resource] ([CultureId], [Key], [Value]) VALUES ('fa-IR', N'Search here...', N'جستجو...')
GO
