--INSERT [dbo].[Localization_Culture] ([Id], [Name]) VALUES ('en-US', N'English (US)')
--GO

INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Account Dashboard', N'Account Dashboard', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Account Information', N'Account Information', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Actions', N'Actions', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Add Address', N'Add Address', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Add another service to log in.', N'Add another service to log in.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Add Attribute', N'Add Attribute', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Add Option', N'Add Option', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Add Review', N'Add Review', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Add to cart', N'Add to cart', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Add to Compare', N'Add to Compare', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Add to Wishlist', N'Add to Wishlist', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Address', N'Address', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Address Book', N'Address Book', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'All', N'All', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'All Categories', N'All Categories', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Apply', N'Apply', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Approved', N'Approved', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Attribute Name', N'Attribute Name', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Available Attributes', N'Available Attributes', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Available Options', N'Available Options', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Brand', N'Brand', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Brands', N'Brands', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Cancel', N'Cancel', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Cart Price Rule', N'Cart Price Rule', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Cart Price Rule Usages', N'Cart Price Rule Usages', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Cart Price Rules', N'Cart Price Rules', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Catalog', N'Catalog', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Catalog.IsCommentsRequireApproval', N'Catalog.IsCommentsRequireApproval', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Catalog.IsProductPriceIncludeTax', N'Catalog.IsProductPriceIncludeTax', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Catalog.ProductPageSize', N'Catalog.ProductPageSize', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Categories', N'Categories', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Category Mapping', N'Category Mapping', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Change', N'Change', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Change password', N'Change password', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Change Password Form', N'Change Password Form', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Choose one', N'Choose one', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'City', N'City', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Clone Product', N'Clone Product', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Code', N'Code', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Comment', N'Comment', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Comments', N'Comments', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Configure', N'Configure', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Confirm new password', N'Confirm new password', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Confirm password', N'Confirm password', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Contact Area', N'Contact Area', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Contact Areas', N'Contact Areas', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Contact name', N'Contact name', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Content', N'Content', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Countries', N'Countries', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Country', N'Country', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'CountryId', N'CountryId', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Coupon Code', N'Coupon Code', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create a new account.', N'Create a new account.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Address', N'Create Address', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Brand', N'Create Brand', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Cart Price Rule', N'Create Cart Price Rule', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Category', N'Create Category', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Contact Area', N'Create Contact Area', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Country', N'Create Country', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Customer Group', N'Create Customer Group', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Menu', N'Create Menu', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Order', N'Create Order', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Page', N'Create Page', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Product', N'Create Product', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Product Attribute', N'Create Product Attribute', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Product Attribute Group', N'Create Product Attribute Group', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Product Option', N'Create Product Option', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Product Template', N'Create Product Template', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create State or Providence', N'Create State or Providence', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Tax Class', N'Create Tax Class', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Tax Rate', N'Create Tax Rate', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create User', N'Create User', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Vendor', N'Create Vendor', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Warehouse', N'Create Warehouse', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Create Widget', N'Create Widget', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Created On', N'Created On', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'CreatedOn', N'CreatedOn', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Cross-sell Products', N'Cross-sell Products', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Current password', N'Current password', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Current Price', N'Current Price', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Current Quantity', N'Current Quantity', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Current theme', N'Current theme', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Customer', N'Customer', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Customer comments', N'Customer comments', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Customer Groups', N'Customer Groups', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Customer reviews', N'Customer reviews', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Customer Service', N'Customer Service', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Dashboard', N'Dashboard', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Date', N'Date', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Default shipping address', N'Default shipping address', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Delete', N'Delete', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Description', N'Description', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Display City', N'Display City', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Display District', N'Display District', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Display Order', N'Display Order', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Display Postal Code', N'Display Postal Code', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'District', N'District', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Download', N'Download', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Edit', N'Edit', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Edit Product', N'Edit Product', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Edit User', N'Edit User', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Email', N'Email', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Enable Stock Tracking', N'Enable Stock Tracking', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'End', N'End', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Enter your email.', N'Enter your email.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Entity Name', N'Entity Name', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Export', N'Export', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'External Logins', N'External Logins', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Forgot your password?', N'Forgot your password?', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Full name', N'Full name', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'FullName', N'FullName', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'General Information', N'General Information', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Global.AssetVersion', N'Global.AssetVersion', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Group', N'Group', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'GTIN', N'GTIN', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Has Options', N'Has Options', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Hello {0}!', N'Hello {0}!', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Home', N'Home', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'hone Number', N'hone Number', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Id', N'Id', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Images', N'Images', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Import', N'Import', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Include in menu', N'Include in menu', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Installed themes', N'Installed themes', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Inventory', N'Inventory', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Is Active', N'Is Active', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Is Allowed To Order', N'Is Allowed To Order', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Is Billing Enabled', N'Is Billing Enabled', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Is Called For Pricing', N'Is Called For Pricing', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Is Featured', N'Is Featured', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Is Published', N'Is Published', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Is Shipping Enabled', N'Is Shipping Enabled', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Is Visible Individually', N'Is Visible Individually', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'IsEnabled', N'IsEnabled', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Latest orders', N'Latest orders', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Log in', N'Log in', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Log off', N'Log off', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Manage', N'Manage', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Manage address', N'Manage address', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Manage Contact', N'Manage Contact', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Manage Contact Area', N'Manage Contact Area', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Manage Cross-sell Products', N'Manage Cross-sell Products', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Manage Related Products', N'Manage Related Products', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Manage Translations', N'Manage Translations', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Manager of Vendor', N'Manager of Vendor', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Managers', N'Managers', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Menus', N'Menus', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Meta Description', N'Meta Description', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Meta Keywords', N'Meta Keywords', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Meta Title', N'Meta Title', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Most search keywords', N'Most search keywords', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Most viewed products', N'Most viewed products', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'My Settings', N'My Settings', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Name', N'Name', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'New Old Price', N'New Old Price', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'New password', N'New password', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'New Price', N'New Price', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'News.PageSize', N'News.PageSize', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'No', N'No', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Not Approved', N'Not Approved', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Not available', N'Not available', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Not Vendor', N'Not Vendor', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Note that the updated translations only be affected after the application is restarted', N'Note that the updated translations only be affected after the application is restarted', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Old Price', N'Old Price', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Option Combinations', N'Option Combinations', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Option Values', N'Option Values', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Order', N'Order', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Order History', N'Order History', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Order Id', N'Order Id', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Order Status', N'Order Status', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Order Total', N'Order Total', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'OrderId', N'OrderId', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Orders', N'Orders', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Pages', N'Pages', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Password', N'Password', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Payment Providers', N'Payment Providers', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Pending', N'Pending', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Pending review replies', N'Pending review replies', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Pending reviews', N'Pending reviews', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Phone', N'Phone', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Phone Number', N'Phone Number', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Postal Code', N'Postal Code', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Posted by', N'Posted by', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Preview', N'Preview', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Price', N'Price', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Attribute Groups', N'Product Attribute Groups', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Attributes', N'Product Attributes', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product detail', N'Product detail', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Documents', N'Product Documents', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Images', N'Product Images', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Name', N'Product Name', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Options', N'Product Options', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Price Management', N'Product Price Management', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Prices', N'Product Prices', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Sku', N'Product Sku', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product specification', N'Product specification', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Templates', N'Product Templates', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Product Variations', N'Product Variations', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Products', N'Products', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Promotions', N'Promotions', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Publish End', N'Publish End', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Publish Start', N'Publish Start', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Rate', N'Rate', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Rate this product', N'Rate this product', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Rating', N'Rating', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Recently viewed products', N'Recently viewed products', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Register', N'Register', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Register as a new user?', N'Register as a new user?', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Related Products', N'Related Products', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Remember me?', N'Remember me?', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Review comment', N'Review comment', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Review Replies', N'Review Replies', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Review title', N'Review title', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'reviews', N'reviews', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Reviews', N'Reviews', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Roles', N'Roles', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Rule Name', N'Rule Name', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Sales', N'Sales', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Save', N'Save', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Search here...', N'Search here...', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Security', N'Security', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Select culture', N'Select culture', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'SEO', N'SEO', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Settings', N'Settings', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Shipment Id', N'Shipment Id', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Shipments', N'Shipments', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Shipping Providers', N'Shipping Providers', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Short content', N'Short content', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Short Description', N'Short Description', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Site', N'Site', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'SKU', N'SKU', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Slug', N'Slug', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Special Price', N'Special Price', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Special Price End', N'Special Price End', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Special Price Start', N'Special Price Start', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Specification', N'Specification', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Start', N'Start', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'State or Province', N'State or Province', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'States or Provinces', N'States or Provinces', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Status', N'Status', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Stock History', N'Stock History', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Stock management', N'Stock management', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Stock Quantity', N'Stock Quantity', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Stocks', N'Stocks', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Submit', N'Submit', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Submit comment', N'Submit comment', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Submit review', N'Submit review', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'SubTotal', N'SubTotal', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'System', N'System', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Tax Class', N'Tax Class', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Tax Classes', N'Tax Classes', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Tax Rates', N'Tax Rates', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Tax.DefaultTaxClassId', N'Tax.DefaultTaxClassId', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'The {0} field is not a valid e-mail address.', N'The {0} field is not a valid e-mail address.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'The {0} field is required.', N'The {0} field is required.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'The {0} must be at least {2} and at max {1} characters long.', N'The {0} must be at least {2} and at max {1} characters long.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'The Email field is not a valid e-mail address.', N'The Email field is not a valid e-mail address.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'The Email field is required.', N'The Email field is required.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'The new password and confirmation password do not match.', N'The new password and confirmation password do not match.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'The password and confirmation password do not match.', N'The password and confirmation password do not match.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Themes', N'Themes', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'There are currently no items in your wish list.', N'There are currently no items in your wish list.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Thumbnail', N'Thumbnail', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Title', N'Title', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Tracking Number', N'Tracking Number', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Translations', N'Translations', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Use', N'Use', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Use a local account to log in.', N'Use a local account to log in.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Use another service to log in.', N'Use another service to log in.', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Users', N'Users', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Value', N'Value', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Vendor Name', N'Vendor Name', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Vendors', N'Vendors', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'View History', N'View History', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'View Online Themes', N'View Online Themes', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Warehouse', N'Warehouse', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Warehouses', N'Warehouses', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Widget Instances', N'Widget Instances', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Widget Type', N'Widget Type', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Widget Zone', N'Widget Zone', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Widgets', N'Widgets', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Wish List', N'Wish List', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Yes', N'Yes', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'You don''t have any default address', N'You don''t have any default address', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'You save', N'You save', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Your account', N'Your account', N'en-US');
INSERT INTO Localization_Resource ([Key], Value, CultureId) VALUES (N'Zip Code', N'Zip Code', N'en-US');

GO
